### ISSUE TITLE
Help window font not correctly rendered

### ISSUE THREAD

**Issue by yunpengn** [nus-cs2103-AY1718S1/forum#100]
It seems that the font used for table of contents and all tables (in all different levels) is not rendered correctly on MacOS. I suspect we need to change the CSS file.

Any suggestion?
<img width="1043" alt="1" src="https://user-images.githubusercontent.com/18503402/31703788-c49d0f54-b410-11e7-89e0-e2f2920560ed.png">

**Comment by damithc** [comment]
Same as #54, let's continue the discussion there.
Unfortunately, there's no proper solution yet :-p
