### ISSUE TITLE
Software to generate sequence diagrams

### ISSUE THREAD

**Issue by szalata** [nus-cs2103-AY1718S1/forum#107]
Could you please tell what software was used for the diagrams that are in the documentation? I see the pptx files, but PowerPoint seems not to be designed for this. I thought about using MS Visio, but then the new diagrams would look differently, thus violating consistency.

**Comment by damithc** [comment]
So far, PowerPoint is the most flexible tool I've found for the job. It allows you to place things in exact position, size, color etc. But you are free to use other tools. It's ok if your diagrams look different from the existing ones (it'll take too much work to redo all diagrams).

I remember some students used Visual Paradigm to generate diagrams in previous semesters.

**Comment by karrui** [comment]
I have been using a plugin someone created for IntelliJ called [SequenceDiagram](https://plugins.jetbrains.com/plugin/8286-sequencediagram)
