### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by Jeremylsw** [nus-cs2103-AY1718S1/forum#11]
Hihi 

Anyone knows how the progress tracker thing works? Can I open my own issue or must I wait till the bot assigns me one? It doesn't assign all the stars too tho like for week 2 there's only progress for 1-star tasks.  

Thanks

**Comment by damithc** [comment]
We'll create issues for you. Week 3 issues will be created soon, possibly tonight. We are waiting for some of the students to accept GitHub invitations.
Week 2 was a trial. We'll create missing week 2 issues (2-stars and above) soon too.

**Comment by Jeremylsw** [comment]
Okayy Thanks!
