### ISSUE TITLE
Request to use JFXtras API

### ISSUE THREAD

**Issue by cctdaniel** [nus-cs2103-AY1718S1/forum#111]
Hi prof @damithc,

This is a request to use the JFXtras API: https://github.com/JFXtras/jfxtras

Thank you.

**Comment by damithc** [comment]
Approved. Note that based on our project constraints, GUI is for output only. Input should come via CLI. While you are allowed to have GUI elements as alternative input mechanisms (e.g. buttons, menu items), they will not earn credit.

**Comment by cctdaniel** [comment]
Noted. I'm planning to use the Agenda class to create a timetable (output).
