### ISSUE TITLE
Failing Travis CI Checks (But Passing on AppVeyor and Intellij)

### ISSUE THREAD

**Issue by teclu** [nus-cs2103-AY1718S1/forum#128]
**Relevant Links**

- PR: https://github.com/CS2103AUG2017-W11-B3/main/pull/27
- Travis Build: https://travis-ci.org/CS2103AUG2017-W11-B3/main/builds/290783574?utm_source=github_status&utm_medium=notification
- AppVeyor Build: https://ci.appveyor.com/project/k-l-a/main/build/1.0.63

Hi everyone,

I've been getting these weird exception errors (_namely java.lang.RuntimeException, caused by java.util.concurrent.ExecutionException, java.lang.ExceptionInInitializerError and java.awt.HeadlessException_) all over my log, even though I did not modify most of the files that are having these problems. However, I'm passing everything on Intellij (on Windows) and AppVeyor.

I've tried enabling and disabling headless mode and rebuilding Travis, but to no avail.

Any help would be much appreciated!

**Comment by damithc** [comment]
Both your computer and AppVeyor are Windows-based, but Travis is Unix-based. Look for OS-sensitive code in your PR, such as hard-coded file paths.

**Comment by teclu** [comment]
Hi Prof, thanks for the quick response!

I do have a hard-coded file path (_the only one in fact_) in one of my classes [here](https://github.com/teclu/main/blob/507608bc592f976e004cc14ed53e9e4145d747e5/src/main/java/seedu/address/model/person/avatar/Avatar.java). If that is the case, must I ensure that this URL path works on both Windows and Unix?

**Comment by damithc** [comment]
Yes, try to get it working on both platforms if possible.
See if you can reproduce the error by running tests in the git-bash shell (the terminal window that comes with SourceTree) in headless mode. That shell has Unix-like behaviors.

**Comment by teclu** [comment]
After much time spent, my PR is finally passing Travis CI's checks! 😀 It wasn't just the file path that was giving the problem; there were many other small problems in my code. Thanks for the help!
