### ISSUE TITLE
Code quality improvements for addressbook-level1: share here

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY1718S1/forum#14]
Students, in [`addressbook-level1/AddressBook.java`](https://github.com/nus-cs2103-AY1718S1/addressbook-level1/blob/master/src/seedu/addressbook/AddressBook.java) if you noticed any [coding standard](https://oss-generic.github.io/process/codingStandards/CodingStandard-Java.html) violations or areas where the code can be improved using best practices mentioned in [our guidelines](https://nus-cs2103.github.io/website/book/codeQuality/), please share them here for the benefit of other classmates.

If you are not sure, you can still post here for the purpose of discussion.

**Comment by damithc** [comment]
https://github.com/nus-cs2103-AY1718S1/addressbook-level1/blob/e013f52873d1441a1b4ede979bc953d19f0f6296/src/seedu/addressbook/AddressBook.java#L797

![image](https://user-images.githubusercontent.com/1673303/29993164-41cbe01c-8fe1-11e7-9c39-7b45f874b5a2.png)


The variable `changed` does not follow the naming convention for boolean variables. Should be `isChanged`?

**Comment by Kennard123661** [comment]
In executeAddPerson(String commandArgs), I think it would be more meaningful if the variable identifier decodeResult on line 420 of AddressBook.java was changed to decodedPersonDetails. 

Reasons: 
* decodeResult sounds like a verb rather than a noun.
* decodedPersonDetails is a more meaningful name than decodeResult (helps reader understand what the contents of the variable are)

**Comment by damithc** [comment]
> In executeAddPerson(String commandArgs), I think it would be more meaningful if the variable identifier decodeResult on line 420 of AddressBook.java was changed to decodedPersonDetails.
> 
> Reasons:
> 
> decodeResult sounds like a verb rather than a noun.
> decodedPersonDetails is a more meaningful name than decodeResult (helps reader understand what the contents of the variable are)

Good point @Kennard123661 👍

**Comment by karrui** [comment]
The parent boolean deletePersonFromAddressBook() should become isPersonDeletedFromAddressBook() to better follow Java naming conventions too, I think.

**Comment by damithc** [comment]
> The parent boolean deletePersonFromAddressBook() should become isPersonDeletedFromAddressBook() to better follow Java naming conventions too, I think.

@karrui The method also deletes the person (which is its main job). Therefore, may be misleading to name `isPersonDeletedFromAddressBook()`? The return value is just to tell us if the deletion was successful.

**Comment by damithc** [comment]
Anybody detected violations of this guideline?

![image](https://user-images.githubusercontent.com/1673303/30000454-029fe4ce-909f-11e7-8576-ed8d27f08d2d.png)

**Comment by deep4k** [comment]
@damithc the method on L:824
`private static void initialiseAddressBookModel(ArrayList<HashMap<PersonProperty, String>> persons) `
should be refactored to 
`private static void initializeAddressBookModel(ArrayList<HashMap<PersonProperty, String>> persons)`

as American spelling is the convention.

**Comment by damithc** [comment]
> @damithc the method on L:824
> private static void initialiseAddressBookModel(ArrayList<HashMap<PersonProperty, String>> persons)
> should be refactored to
> private static void initializeAddressBookModel(ArrayList<HashMap<PersonProperty, String>> persons)
> 
> as American spelling is the convention.

Yup. @deep4k 👍
