### ISSUE TITLE
Weird travis build error

### ISSUE THREAD

**Issue by shuang-yang** [nus-cs2103-AY1718S1/forum#141]
Hi Guys! 

I have been receiving these repeating error messages from travis:
![image](https://user-images.githubusercontent.com/27795623/32023309-6a0db484-ba0b-11e7-924c-622509e80927.png)

However, all the classes in the error message are already defined and exist precisely in the specified location. Local tests also did not report any error.

Does anyone know why this keeps happening?

**Comment by damithc** [comment]
@shuang-yang can you give the link to your PR?
Ensure those classes are committed and your branch is synced with upstream master.

**Comment by shuang-yang** [comment]
Hi Prof! Here is the link to my PR: 
https://github.com/CS2103AUG2017-T14-B3/main/pull/44

**Comment by damithc** [comment]
@shuang-yang The error in the Travis log of that PR is different from your screenshot.

**Comment by damithc** [comment]
@shuang-yang Is this issue still relevant? Close if not.

**Comment by shuang-yang** [comment]
Hi Prof! Sorry I forgot to follow up on this - it was fixed! I'll close this now.
