### ISSUE TITLE
.jar file has error

### ISSUE THREAD

**Issue by Juxarius** [nus-cs2103-AY1718S1/forum#143]
Hi, so this week's milestone requires us to create a milestone and i have problems creating it.

1. Method 1: Using gradlew shadowJar
my gradlew is not able to resolve JavaFX imports even tho i used gradle to import the project in the first place and since this prevents gradlew from building the project, the shdowJar command fails as well

2. Method 2: Using IntelliJ
Referring to online sources,
File > Project Structure > Artifacts > + > select mainApp > OK
Build > Artifacts > Build
This produces a .jar file but it doesnt not work after clicking it. If i use a console to run it, it returns:
`No main manifest attribute`
I have tried putting the MANIFEST .MF file in the java folder and the resources folder but the same error occurs

Thanks in advance for any help!

**Comment by damithc** [comment]
Other members of your team has the same problem? Only one of you need to generate the jar.

**Comment by Juxarius** [comment]
Yes most of us do.
Only 1 person can run gradlew properly but he was sick and absent.

**Comment by damithc** [comment]
Did you guys post  here about the original gradle problem or try to fix it. e.g. redo the set up with more careful attention to setup instructions?

**Comment by Juxarius** [comment]
Sry we failed to post here abt the original gradle problem because we just did the direct Junit testing via intelliJ. Will try re-importing.

**Comment by Juxarius** [comment]
Deleted local repo and re-cloned.
Ran gradlew processResources.
Status still same, JavaFX is not recognised

**Comment by damithc** [comment]
Can you post more details about the error? What's output when you run the gradle task?

**Comment by Juxarius** [comment]
the error comes in `:compileJava` where every single use of javafx in the code gives an error, a total of 100 errors.
all saying `package javafx.* does not exist`

https://gyazo.com/2f99e07192f27d24f71f355bc252ed90

**Comment by tshradheya** [comment]
> You must include in the Project in your IDE the jfxrt.jar otherwise it will not be included as this was the default behavior prior to Java 8.
> 
> Then depending on your system and the way your build your jar for your project, and it also must be there for running the jar. So make your project also export the required libraries.

Quoted from https://stackoverflow.com/questions/24361270/javafx-packages-not-found

I guess you should check if you are using JAVA 8 or later?
Also if you are using windows, ensure your environment variables are correct. For e.g. JAVA_HOME points to jdk1.8

**Comment by damithc** [comment]
As a sanity check, do this:
* clone our AB4 repo (not your repo) to a fresh location
* run `./gradlew shadowJar`

See if that works. I did it just now and there were no errors. 

BTW, are you on Windows or Mac?

**Comment by Juxarius** [comment]
assertSanity fails i guess, the compileJava continues to give the same response, so im guessing this is a problem with my system?

I am on windows

tried doing a PR from module repo to my remote repo, GitHub tells me there is nothing to PR

**Comment by tshradheya** [comment]
https://stackoverflow.com/questions/1672281/environment-variables-for-java-installation

Check your environment variables using the above link. If it is set to Java 7 or below then it could be the problem of JAVAFx not being imported by default.

**Comment by Juxarius** [comment]
omg you are right! it was my environment variables causing the trouble, apparantly my JAVA_HOME was pointing to the scoop folder which does not have the javafx files.

Thank you so much! Thanks Prof for the quick response too!
