### ISSUE TITLE
background colour issues of browserpanel

### ISSUE THREAD

**Issue by itsdickson** [nus-cs2103-AY1718S1/forum#144]
Hi everyone,

My group's application allows the switching of colour themes through different CSS files (themes files). 

However, the BrowserPanel default background colour does not change according to the theme. I realise that it follows the background colour of the theme set on default.html, and it does not seem like we can set 2 CSS files onto the default.html file as so: 

![image](https://user-images.githubusercontent.com/30717938/32038468-ad79b73a-ba5c-11e7-8e74-f93af45fe24e.png)

Hence, with the code above, the background colour of the BrowserPanel is set to BrightTheme's background colour, as shown below:

![image](https://user-images.githubusercontent.com/30717938/32038512-e37ec6b8-ba5c-11e7-877e-fc1af3128b75.png)

This is how the BrowserPanel window will look like when it's not filled with a website. Any ideas how to fix this? 

Thanks in advance!

**Comment by hansiang93** [comment]
For CSS files, how the browser does the themes is by loading both the values within CSS, and selecting the one with the highest priority. Loading both the dark and light themes at the same time would not place you in control on how the browser chooses to load the CSS to use ( as this is a browser centric thing).

Also, this "default" background is basically a local website with the color scheme loaded.

Instead, you could create a new "defaultLight.html" that loads a different CSS, and using the method that you use to change the theme, to point that browser to the different "defaultLight.html".

**Comment by itsdickson** [comment]
Thanks @hansiang93 for the help! It works and thanks once again!
