### ISSUE TITLE
Post here if you cannot access progress repo

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY1718S1/forum#15]
CS2103/T students,
Post here (**include your name and tutorial slot** for cross checking) if you cannot access the [nus-cs2103-AY1718S1/progress](https://github.com/nus-cs2103-AY1718S1/progress) or you do not have any issues **correctly assigned to you** in [that issue tracker](https://github.com/nus-cs2103-AY1718S1/progress/issues)

**Comment by martyn-wong** [comment]
Sorry Prof, but I do not have access

**Comment by damithc** [comment]
> Sorry Prof, but I do not have access

@martyn-wong can you give your name and tutorial slot too? Thx.

**Comment by martyn-wong** [comment]
Actually, I managed to find to find my issues by manually searching my name instead of using the filters. Probably due to a mismatch in my Github ID.
Sorry for the inconvenience and thanks Professor.

**Comment by damithc** [comment]
> Actually, I managed to find to find my issues by manually searching my name instead of using the filters. Probably due to a mismatch in my Github ID.

Tutor @Skaty FYI `Martyn Wong Hao Ren` -> @martyn-wong

**Comment by qihao27** [comment]
Sorry prof, I also can't access that page....

**Comment by damithc** [comment]
> Sorry prof, I also can't access that page....

@qihao27 What's your name?

**Comment by KhawYewOnn** [comment]
Hey Prof, I can't access the page as well. I got "page not found". 
My name is Khaw Yew Onn, Tutorial group is 2.

**Comment by damithc** [comment]
> Hey Prof, I can't access the page as well. I got "page not found".
> My name is Khaw Yew Onn, Tutorial group is 2.

@KhawYewOnn We sent an invitation to you long ago. You haven't accepted it yet. Go to https://github.com/nus-cs2103-AY1718S1 to accept invitations.

**Comment by qihao27** [comment]
@damithc Wu Qihao from tutorial group C04

**Comment by damithc** [comment]
> @damithc Wu Qihao from tutorial group C04

Invitation sent. Tutor @Skaty FYI

**Comment by qihao27** [comment]
Thanks prof, but I don't have any issues assigned to me.

**Comment by damithc** [comment]
> Thanks prof, but I don't have any issues assigned to me.

@qihao27 You can search for your name (in issue title) and assign them to yourself. As you submitted the github username late, we were unable to assign issues to you until now.

**Comment by qihao27** [comment]
@damithc Thanks for your help prof

**Comment by khooroko** [comment]
Hi Prof Damith, I was redirected here by a bot from my pull requests.
Tutorial group C05, Khoo Wei Ping. 
Lin Jiachao and Kennard Ng Pool Hua from tutorial group C06 are facing the same issue.

**Comment by damithc** [comment]
> Hi Prof Damith, I was redirected here by a bot from my pull requests.
> Tutorial group C05, Khoo Wei Ping.
> Lin Jiachao and Kennard Ng Pool Hua from tutorial group C06 are facing the same issue.

@khooroko Noted. We'll update our list of github username for the three of you.

**Comment by danielbrzn** [comment]
Hi Professor, my github username is not recognised as well.

**Comment by damithc** [comment]
> Hi Professor, my github username is not recognised as well.

Noted @danielbrzn. We'll add it to the list.

**Comment by ALim95** [comment]
Hi prof, I dont have any issues assigned to me as well.
Alpheus Lim from T15

**Comment by damithc** [comment]
> Hi prof, I dont have any issues assigned to me as well.
> Alpheus Lim from T15

@ALim95 I assigned you the issues just now.

**Comment by lancehaoh** [comment]
Hi prof, my username is not recognized by the system.

**Comment by damithc** [comment]
> Hi prof, my username is not recognized by the system.

@lancehaoh Added. Tutor @Skaty FYI.

**Comment by Phuajunjie** [comment]
hi prof, my Github username is not recognized. Im from T11/A2.

**Comment by damithc** [comment]
> hi prof, my Github username is not recognized. Im from T11/A2.

Noted @Phuajunjie You can ignore the warning for the time being.

**Comment by Lenaldnwj** [comment]
Hi prof, my Github username is not recognised too. I'm from T16-A2.

**Comment by damithc** [comment]
> Hi prof, my Github username is not recognised too. I'm from T16-A2.

Noted @Lenaldnwj  You can ignore the warning for the time being.

**Comment by seankwekjk** [comment]
Hi prof, my Github username is not recognised. I'm from T16-A2

**Comment by damithc** [comment]
> Hi prof, my Github username is not recognised. I'm from T16-A2

Noted @seankwekjk
Tutor @louislai, for your action (i.e. update pr-bot)

**Comment by Chng-Zhi-Xuan** [comment]
Hi prof, I received an email saying my github username is not recognized after creating a PR to addressbook-level2. I have access to the progress tracker repo.

**Comment by damithc** [comment]
> Hi prof, I received an email saying my github username is not recognized after creating a PR to addressbook-level2. I have access to the progress tracker repo.

@Chng-Zhi-Xuan did you use a different username `Botasky7` earlier?

**Comment by Chng-Zhi-Xuan** [comment]
Oh yes I did. I changed my user name to be less "for games". Sorry for any inconveniences caused.

**Comment by damithc** [comment]
> Oh yes I did. I changed my user name to be less "for games". Sorry for any inconveniences caused.

Noted @Chng-Zhi-Xuan 
Tutor @louislai FYI

**Comment by jelneo** [comment]
Hi Prof, sorry for the inconvenience. I have changed my github id from `b02b01` to `jelneo`.

**Comment by damithc** [comment]
> Hi Prof, sorry for the inconvenience. I have changed my github id from b02b01 to jelneo.

Noted @jelneo 
tutor @Skaty FYI

**Comment by YuanQLLer** [comment]
Hi Prof, sorry for the inconvenience. I have changed my github id from LLercpp to YuanQLLer.
