### ISSUE TITLE
Will this violate SRP

### ISSUE THREAD

**Issue by junming403** [nus-cs2103-AY1718S1/forum#152]
Hi prof, recently I write a command Remark, however, i am reluctant to write one more separate command like 'deleteRemark' to support delete operation because it sounds stupid... I am thinking of using some command like `remark -d [INDEX]` to support it. There is several way to implement it.
1. Support multiple ways of execution in RemarkCommand (A switch branch in execute method).
2. Create different commands according to the parsing result of RemarkCommandParser. Then a RemarkCommandParser could return a normal remark command or a delete remark command.

However, I am not sure which way is better, or in both cases, will SRP being considered violated?

**Comment by charlesgohck** [comment]
I suggest adding remarks as a field. It functions like one anyway. After you implement add, edit, delete etc I think you can just call these functions, you could probably use them if you decide you want an additional command.

**Comment by junming403** [comment]
Ummm our app is no longer about person. Thus there is no filed anymore..

**Comment by charlesgohck** [comment]
Oh, pardon me. I did not realise that...

**Comment by RonakLakhotia** [comment]
Hi Junming,

1. Considering your first approach, it would violate the SRP principle for the simple reason that the RemarkCommand class should change only for one reason (according to the SRP principle) that is the class should have only one functionality.Hence handling a delete operation inside the Remark command should not be the ideal way forward.

 2. Could you further clarify on your second approach?

**Comment by Kennard123661** [comment]
Wait... Do you really need a flag -d to delete a remark, wouldn't an empty remark be equivalent to no remark? (I think a better idea would be to create a static instance of an empty Remark that is assigned to each person) You can't edit this static Remark object or create it. 

so your delete remark works like this. If the user enters an empty remark (i.e. remark only has whitespaces) then "delete" remark, give it the empty remark instance. You don't need to implement a new command and its easier for the user. And if you are gonna add flags, I think it would encourage other contributors to start adding flags, then your commands will start having flags and get a bit too clunky for the average user (just an opinion)

**Comment by tshradheya** [comment]
First of all, avoid using -d in the command. It is something absurd as all other commands have syntax in a different manner. 

My tutor @okkhoy suggested a team not to use `-send` because it will confuse the user.

I agree with @Kennard123661 that is just unnecessary to make a new command for something that can be done using the same command as suggested in Appendix A.2 of Developer guide of AB4

**Comment by junming403** [comment]
Thank you for your response.
