### ISSUE TITLE
How to export a resource folder into Jar 

### ISSUE THREAD

**Issue by wishingmaid** [nus-cs2103-AY1718S1/forum#157]
I want to export a resource folder along with the AddressBook app such that when I click the executable jar application, it generates a folder which I can store and call my images from(similar to when clicking the executable jar file , it generates the config and preferences json files.) Any help will be very much appreciated.

**Comment by karrui** [comment]
Please do take a look at my commit https://github.com/CS2103AUG2017-F11-B3/main/commit/ba3028906851884bf91f7964dee7140dea64d2a2

May not be the best way, but that's how I did it! Please do let me know if you found a better way so I can update mine too!

**Comment by tshradheya** [comment]
Have a look at the `init()` function in `MainApp.java`. 

You will need to understand how the `data`  folder for xml address book is created through `preferences.json` and carry out a similar approach.

I have done something similar in this [PR](https://github.com/CS2103AUG2017-W14-B1/main/pull/120/files)

However I am currently working on improving the design for it, but it is something like this

Also, would like to point out that `.jar` file is like a zipped folder so technically you cannot export a folder `into` jar. You are rather creating one in the same directory as the `.jar`

**Comment by wishingmaid** [comment]
Thanks for the useful tips! Just curious though , @karrui you created a data/avatar/ as your output filepath for your image folder.  I am assuming that goes into the folder that stores address.xml. That means that if the your data in addressBook has not been saved, then the avatar folder will not be created. Because I simply created a folder using `file.mkdir()` upon the first execution of addressBook, is there any benefit from this mode of implementation or is it just a preference?

**Comment by karrui** [comment]
@wishingmaid 
It will create a folder if it does not exist regardless of whether the data has or has not been saved, as the avatar folder check is instantiated during the initialization of the application.

I was planning to allow the user to specify the location for the avatar through config.json, but I got so burnt out implementing it that I pushed it to v2.0.

**Comment by wishingmaid** [comment]
@karrui I see, thanks for you input on this matter. 
@tshradheya thank you for your suggestion as well.
