### ISSUE TITLE
Editing all PersonCards via PersonListPanel

### ISSUE THREAD

**Issue by charlesgohck** [nus-cs2103-AY1718S1/forum#161]
I'm working on buttons to increase and decrease font sizes on the go. However, it seems that unlike the handleHelp() handler, my buttons cannot trigger the handlers. I essentially based my implementation off the way handleHelp interacts with its corresponding onAction field. 

This is my declaration for the menu items:
![screen shot 2017-10-30 at 7 31 39 pm](https://user-images.githubusercontent.com/15852016/32168920-5ad33466-bda9-11e7-94ea-d435808a234a.png)

This is my onAction field
<img width="292" alt="screen shot 2017-10-30 at 7 32 14 pm" src="https://user-images.githubusercontent.com/15852016/32168943-6f7390e6-bda9-11e7-9d02-b27483e505b4.png">

And these are my handler functions:
![screen shot 2017-10-30 at 7 31 47 pm](https://user-images.githubusercontent.com/15852016/32169052-d4783488-bda9-11e7-912f-82430de2a892.png)

They link to other classes but the point is that the logger did not log any activity at all when I clicked on the buttons. I scoured stackoverflow for answers but did not have any luck. I did notice a few posts that said that if you don't link the controller with the view then it might cause NullPointerExceptions. Probably not related but might be worth mentioning.

Has anyone encountered this issue where the event handler is not responding to the triggers?

**Comment by charlesgohck** [comment]
**Update:** Seems like the problem lies in the logger message priority. Changed it to info priority and it logs now. 

Has anyone done a similar enhancement that edits the PersonCard UI on the fly? This is my current implementation (links to PersonCard which executes the change of font sizes) but I'm afraid that it is not working because of the ListView's conversion to ObservableList:
![screen shot 2017-10-30 at 7 42 15 pm](https://user-images.githubusercontent.com/15852016/32169250-b87ff8c8-bdaa-11e7-885c-b259ff70484c.png)

**Comment by charlesgohck** [comment]
Update: Got it to work by setting a new connection in PersonListPanel class. See relevant PR for more information for people who might want to do this:
https://github.com/CS2103AUG2017-W09-B2/main/pull/92

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
