### ISSUE TITLE
Trying to toggle between personListPanel and EventsListPanel

### ISSUE THREAD

**Issue by archthegit** [nus-cs2103-AY1718S1/forum#162]
I am trying to switch between the two, and while the switch is successful, the person list panel doesn't allow me to scroll or select while my events list panel does. Has anyone faced this?

this is the codeine the MainWindow.fxml to switch between the two panels
<img width="400" alt="screen shot 2017-10-30 at 11 19 43 pm" src="https://user-images.githubusercontent.com/22144490/32178870-d8dd3e78-bdc8-11e7-82f9-4f6198c99437.png">
<img width="300" alt="screen shot 2017-10-30 at 11 15 30 pm" src="https://user-images.githubusercontent.com/22144490/32178762-84a18968-bdc8-11e7-9e52-d327e76f4c9f.png">
<img width="300" alt="screen shot 2017-10-30 at 11 17 16 pm" src="https://user-images.githubusercontent.com/22144490/32178764-85dde0b0-bdc8-11e7-874e-f060340311f5.png">

**Comment by damithc** [comment]
Perhaps you can first try to have both panels side-by-side? Once you get that working, you can try to toggle, which I assume is more complicated than the side-by-side option.

Also, it will help if you post the link to your PR here

**Comment by archthegit** [comment]
I tried putting the person list on top and the events list at the bottom and it works fine. 

This is the link to my PR:
[https://github.com/CS2103AUG2017-T15-B3/main/pull/98](url)

Thank you!

**Comment by damithc** [comment]
@archthegit any success?

**Comment by archthegit** [comment]
Nothing yet :( changing the order of the stack panes, makes the first stack pane work. Still trying to see what the issue is

**Comment by tshradheya** [comment]
Try using `personListPanelPlaceholder.getChildren().clear()` instead of `.remove()`
Also check if `selectionModel()` of the list is changed as well inside the function. ( **This should solve the problem** )

Also, I noticed that you have both lists in the same pane, then you can try using `.toFront()` for the ListView.
My teammate @justinpoh used it for toggling between two panes in the same panel.
All you have to do it add both ListView in the same panel and keep toggling by using `.toFront()`
Here is his [PR](https://github.com/CS2103AUG2017-W14-B1/main/pull/100/files)

**Comment by archthegit** [comment]
@tshradheya thanks! I am trying it out now. However i am unclear on what you mean by the selectionModel() do you mean the function that switches between the two panes?

**Comment by tshradheya** [comment]
Each list has its own `selectionModel()` which gets triggered on the `setEventHandlerForSelectionChangeEvent()`  in your `EventsListPanel.java`

Since this function is only called in constructor it might be the reason that when you switch the lists it doesnt't update and hence you cant't select

**Comment by damithc** [comment]
@archthegit any progress?

**Comment by archthegit** [comment]
Hi Prof,
Yes my team mate has managed to solve it.

**Comment by damithc** [comment]
Great. In that case go ahead and close the issue.
