### ISSUE TITLE
Travis Error: An error occurred while generating the build script.

### ISSUE THREAD

**Issue by cctdaniel** [nus-cs2103-AY1718S1/forum#164]
Hi, as stated in the title, I am having a problem with Travis CI, and it's giving me this error. I can pass AppVeyor though. I'm not sure what is the problem here in this case.

Here is the link to my PR: https://github.com/CS2103AUG2017-W13-B4/main/pull/242

**Comment by damithc** [comment]
@tshradheya is this related to the Travis error you observed?

**Comment by tshradheya** [comment]
@damithc Yes prof.

I noticed this problem around 2-3 hours back and it is still not resolved by Travis people

![image](https://user-images.githubusercontent.com/12574756/32214696-adf2a4d6-be5a-11e7-9325-c1ca18085de7.png)

**Comment by damithc** [comment]
> @damithc Yes prof.
> 
> I noticed this problem around 2-3 hours back and it is still not resolved by Travis people

Thanks for checking. Guess we'll have to wait it out and rely on AppVeyor for the time being.

**Comment by cctdaniel** [comment]
Okay noted prof.

**Comment by tshradheya** [comment]
Hello. 
Looks like the problem is almost fixed. You can restart the build on Travis CI to check your tests

**Comment by cctdaniel** [comment]
Alright thanks!
