### ISSUE TITLE
Travis CI Permission Denied

### ISSUE THREAD

**Issue by LeeYingZheng** [nus-cs2103-AY1718S1/forum#170]
Hi friends, 
I encountered an issue with Travis CI with the following message. I was wondering if anyone knows what this is, cause I tried searching for the issue online and tried multiple solutions but it still gave me this result.
![travispermissiondenied](https://user-images.githubusercontent.com/31031508/32282127-b4de857e-bf5b-11e7-8427-1fb1b3494a92.png)
It all started when I tried pulling changes from my remote repo to my local repo but due to new folders present in my remote repo source tree didn't allow me to pull those changes. I tried recloning my repo but source tree still gave me an error, so I downloaded the whole project repo and made sure all the set ups were the same before working on the code until I came to this error when I made a PR

**Comment by damithc** [comment]
Which OS are you using?

**Comment by damithc** [comment]
Also, post a link to the PR in concern

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
