### ISSUE TITLE
Collate-TUI tool not collating code for .xml file

### ISSUE THREAD

**Issue by huyuanrong** [nus-cs2103-AY1718S1/forum#171]
Hi guys, for our application I've populated a default list of values (touristbook.xml).

I ran the command _java -jar Collate-TUI.jar collate from src/main to collated/main include java, fxml, css, xml_

However, the name.md file inside the collated folder does not contain the values that I have written.

Some advice would be appreciated!

P.S. I'm not too sure about the code marking in the .xml file, so I followed the .fxml style of code marking

**Comment by damithc** [comment]
@huyuanrong you need to give link to the file in concern so that someone can check if the file is annotated correctly.

**Comment by RonakLakhotia** [comment]
@huyuanrong make sure the path you mention in the collate command is correct, I have attached a picture below for reference.
In the command I used, I specified the path as data/useraddressbook.xml as that is where my file is located.
Hope this helps.
<img width="1275" alt="collate" src="https://user-images.githubusercontent.com/28557842/32313512-46e5252c-bfde-11e7-98ee-016f23a1b88e.png">

**Comment by huyuanrong** [comment]
@RonakLakhotia Hey, thanks a lot! That worked for me. 

However, it would overwrite the rest of the code that was collated in name.md 

What I did was to just put the .xml file inside src/main folder, then run the same command that I initially typed, and it worked. Hope anybody else facing this issue will take note of the folder directory!

@damithc Thanks prof as well!
