### ISSUE TITLE
Issue with JFileChooser and FileDialog on Mac OS

### ISSUE THREAD

**Issue by liliwei25** [nus-cs2103-AY1718S1/forum#174]
Hi guys,

I'm having some issues with JFileChooser/FileDialog on Mac. I am using the file chooser to allow user to select which image file they would like to set for their contact. Everything is working fine on Windows but when the function is called on Mac, it hangs and the rainbow spinner comes out but no error/exception shows on the terminal :/

This is a snippet of my code for reference:
![image](https://user-images.githubusercontent.com/22389228/32315086-aaed408e-bfe5-11e7-8399-07fab0166989.png)

I have tried JFileChooser for mac and it didnt work so I Googled and there were suggestions to use FileDialog. But it still didn't work after changing it so it would be great if anyone could provide some insight on this.

Thanks in advance!

**Comment by damithc** [comment]
Not a solution but I assume you followed a tutorial like this? https://docs.oracle.com/javafx/2/ui_controls/file-chooser.htm

**Comment by liliwei25** [comment]
@damithc Thanks for the help prof! I changed JFileChooser to FileChooser and I was able to get it to show on both platforms!
