### ISSUE TITLE
When to use assertions

### ISSUE THREAD

**Issue by justintkj** [nus-cs2103-AY1718S1/forum#175]
May i ask if it is appropriate to use assertion in tests?

public class FavouriteCommandParserTest {

   public static final String FIRST_PERSON = "1";
   private FavouriteCommandParser parser = new FavouriteCommandParser();

   @Test
   public void parse_validArgs_returnsFavouriteCommand() {
       try {
           assertParseSuccess(parser, FIRST_PERSON, new FavouriteCommand(INDEX_FIRST_PERSON,
                   new Favourite(FIRST_PERSON)));
       } catch (IllegalValueException ive) {
           assert FIRST_PERSON == "1";
       }
   }

In this case, I need to do a catch to validate the Favourite Object, however, it would never be illegal value. It's incorrect to leave a catch block empty too.

**Comment by damithc** [comment]
Not directly related. Just a tip about formatting code in markdown: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by tshradheya** [comment]
To compare strings you should be using `.equals()` instead of `==`
 
I think you can `throw new IllegalArgumentException("illegal");` in the catch block

**Comment by karrui** [comment]
If you do not expect any exceptions, you can throw it out without a try-catch block like:
`public void parse_validArgs_returnsFavouriteCommand() throws IllegalValueException {}`

**Comment by justintkj** [comment]
Thanks for all the prompt replies! Issue solved!

**Comment by damithc** [comment]
To answer the original question _is it OK to use `assert` in tests?_, there is no rule against it but recommended to use JUnit `assert*` methods instead. Although Intellij automatically enables asserts for JUnit tests, other IDEs might not, and Travis might not either. i.e. your `assert`s in Tests might not even be executed.
