### ISSUE TITLE
Travis CI-build Failed due to regex changes

### ISSUE THREAD

**Issue by kaiyu92** [nus-cs2103-AY1718S1/forum#177]
Hi friends,
I've encountered an issue with Travis CI and I cannot find the root of the problem. 

**Context:**
I've created a Datetime class which acts an attribute for an Event object. Initially, I put DATETIME_VALIDATION_REGEX as "[^\\s].*" (which obviously is the incorrect format). After realising the incorrect format, I try to rectify it by changing to "((0[1-9])|([012][0-9])|(3[01]))-(0[1-9]|1[012])-\\d\\d\\d\\d (([0-1][0-9])|(2[0-3]))[0-5][0-9]". Then I make a PR at my organisation repo. 

However, Travis have prompt a list of problem which I don't know where to start from and how does it link to me changing the regex (as the problem prompts by Travis CI are mainly GUI issues: Refer to the screenshot below) Additionally, I have also tried running "./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls asciidoctor" in my IntelliJ Terminal, it doesn't prompt me any error with the new regex.  

![image](https://user-images.githubusercontent.com/24559155/32330746-035fdf02-c01c-11e7-87be-40e6d3a9d9e4.png)

The previous incorrect regex ("[^\\s].*") does not have this issue, is only when I changed to a new regex.

More information:
OS used: MAC OS
PR link: https://github.com/CS2103AUG2017-T14-B2/main/pull/98/files

**Comment by damithc** [comment]
If it passes locally but fails on Travis and the only difference is the regex, one possibility is that the regex parsing takes too much resources, more than the limited amount of resources allocated to you by Travis.

**Comment by tshradheya** [comment]
@kaiyu92 I have had friends who had tried to use similar regex for Birthday and got the tets to pass on Travis. (I doubt if they had to change anything to take care of resources provided by Travis for parsing)

@damithc How do we actually go about checking how much amount of resources is allocated by us to Travis? Since only his GuiTests and SystemTests are failing, could the fix be something to change in the GuiRobot.java ?
The actual test to check validity of dates `public void isValidDate()` is passing but only guiTests and SystemTests seem to have a problem.

**Comment by Juxarius** [comment]
When i tried regex, i realise it is abit different for java. There should be double backslashes unless you did that and the post ignores the 1st one.

Also if your parser is causing too much trouble, feel free to use [this](https://github.com/nus-cs2103-AY1718S1/forum/issues/167)

**Comment by kaiyu92** [comment]
@damithc @tshradheya @Juxarius Firstly, Thank you so much for the help. I've try other ways to validate the format of the Datetime. Basically, I used if else to check for the Datetime (refer to the code below).

    /**
     * Returns true if a given string is a valid event datetime.
     */
    public static boolean isValidDatetime(String test) {
        Boolean validTime = false;
        Boolean validDate = false;

        if (test.length() != VALID_DATETIME_LENGTH) {
            return false;
        }

        try {
            int day = Integer.parseInt(test.substring(0, 2));
            int month = Integer.parseInt(test.substring(3, 5));
            int year = Integer.parseInt(test.substring(6, 10));
            int hour = Integer.parseInt(test.substring(11, 13));
            int min = Integer.parseInt(test.substring(13, 15));

            //Check Time Validation
            if (0 <= hour && hour <= 23) {
                if (0 <= min && min <= 60) {
                    validTime = true;
                }
            }

            //Check Date Validation
            if (day >= 1) {
                // For months with 30 days.
                if ((month == 4
                        || month == 6
                        || month == 9
                        || month == 11)
                        && day <= 30) {
                    validDate = true;
                }
                // For months with 31 days.
                if ((month == 1
                        || month == 3
                        || month == 5
                        || month == 7
                        || month == 8
                        || month == 10
                        || month == 12)
                        && day <= 31) {
                    validDate = true;
                }
                // For February.
                if (month == 2) {
                    if (day <= 28) {
                        validDate = true;
                    } else if (day == 29) {
                        if ((year % 4 == 0 && year % 100 != 0) || year % 400 == 0) {
                            validDate = true;
                        }
                    }
                }
            } //else date is not valid
        } catch (NumberFormatException e) {
            return false;
        }
        return validTime && validDate;
    }

However, Travis CI still prompted me the same problem.

PR: https://github.com/CS2103AUG2017-T14-B2/main/pull/98

Regards,
Quek Kai Yu

**Comment by jelneo** [comment]
Hi Kai Yu, maybe you can start by choosing a test and using the debugger to step through each step to find out where the `IllegalValueException` is thrown and and which variable caused the error

**Comment by kaiyu92** [comment]
@jelneo Thanks for the help and apparently I miraculously solved it, which I don't know how did I do it.
