### ISSUE TITLE
VBox does not contain itself

### ISSUE THREAD

**Issue by Juxarius** [nus-cs2103-AY1718S1/forum#184]
Hi guys, i got a problem here that i cant really detect the error since the UI cannot be debugged

![image](https://user-images.githubusercontent.com/31033417/32384125-d7d41496-c0f4-11e7-80d3-fb94857b685c.png)

So above is the layout of my profile which i have put in scenebuilder and you can see from the fxml file below, no fx:id or additional style changes have been made to the VBoxes

![image](https://user-images.githubusercontent.com/31033417/32384197-0e36d55a-c0f5-11e7-9b94-b1eea7563e05.png)

However, when i run the App, all my bindings are right, except that the 2nd VBox in the Hbox seems to have flooded the entire centre panel

![image](https://user-images.githubusercontent.com/31033417/32384240-3b1b1e0a-c0f5-11e7-9687-a802ff5ac98a.png)

Can see that the VBox is handled with default VBox formatting but i have no idea where i have gone wrong since the VBox doesnt have an fx:id, i dont think the code could have made it out of place, and the 1st VBox was placed properly but not this one, i have tried using a 1 by 2 GridPane but the same result occurs

Thanks in advance for any help!

**Comment by damithc** [comment]
@Juxarius is there any link to the PR so that the reader can see the diff to the fxml file?

**Comment by Juxarius** [comment]
oh yea, the .fxml file is InsuranceProfilePanel and can be found in [this PR](https://github.com/CS2103AUG2017-T13-B1/main/pull/133/files#diff-03982a5ccde2abc3fa3e56e8fb80d9cf)
The overall PR is found [here](https://github.com/nus-cs2103-AY1718S1/addressbook-level4/pull/45/files)

**Comment by damithc** [comment]
You need to isolate the problematic code if you want someone to examine it. May be create a tiny PR that only has the code related to this problem?

![image](https://user-images.githubusercontent.com/1673303/32412780-9e0222cc-c23d-11e7-814d-44296d901b62.png)

**Comment by Juxarius** [comment]
feature uses a lot of other code so it is hard to isolate, however, implementing it on a clean addressbook doesnt seem to have this issue, ill figure it out on my own, thanks for the advice

**Comment by Juxarius** [comment]
Problem solved, the scrollPane had a default white background when a style class isnt added, it was the one fogging the screen
