### ISSUE TITLE
Travis CI Build Errors - Not from code written

### ISSUE THREAD

**Issue by reginleiff** [nus-cs2103-AY1718S1/forum#193]
I had recently made a new PR which involved changing some implementation of events, but have managed to run all tests successfully on my local machine.

![image](https://user-images.githubusercontent.com/22815234/32449554-d8f69d4e-c34c-11e7-9bca-ea95216258b0.png)

However, the Travis CI build online seems to fail due to strange errors which do not indicate any problem on code that I have written. Does anyone have an idea as to the reason why?

![image](https://user-images.githubusercontent.com/22815234/32449685-3807418a-c34d-11e7-9581-89365032d5aa.png)

**Links:**
PR: https://github.com/CS2103AUG2017-T14-B3/main/pull/89
Travis CI Log: https://travis-ci.org/CS2103AUG2017-T14-B3/main/jobs/297454169

**Comment by damithc** [comment]
Can you pass tests in headless mode locally?

**Comment by damithc** [comment]
Some things you can try:
* Restart the Travis build to confirm it was not a temporary error
* Get one of your team members to pull your branch and try to run the tests locally, to see if it is caused by your local set up (e.g. you have a local file that is not present in Travis environment)

**Comment by damithc** [comment]
Any progress?

**Comment by reginleiff** [comment]
I had gotten my teammate to pull my branch to test on his local machine, and it failed as per the online build test. However, we could not isolate the problem in time for the v1.5rc release, so we decided to abandon the feature. Thank you for the assistance @damithc!
