### ISSUE TITLE
Issue about release after using external library

### ISSUE THREAD

**Issue by Adoby7** [nus-cs2103-AY1718S1/forum#194]
Hi all,
Our team use FontAwesomeFx API, and import this library into project.
When we want to create .jar file by "gradlew shadowJar", the .jar file cannot run because this library is not included.
How to fix it?

**Comment by damithc** [comment]
Not a solution but a quick comment: when adding a new dependency, you need to add it by modifying gradle files, not using Intellij

**Comment by marvinchin** [comment]
Have you included the library to your gradle.build file? It should be added under the `dependencies` section.
```
dependencies {
        compile group: 'org.fxmisc.easybind', name: 'easybind', version: '1.0.3'
        compile "org.controlsfx:controlsfx:$controlsFxVersion"
        compile "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion"
        compile "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jacksonDataTypeVersion"
        compile "com.google.guava:guava:$guavaVersion"
        compile group: 'org.facebook4j', name: 'facebook4j-core', version: '2.4.10'

        testCompile "junit:junit:$junitVersion"
        testCompile "org.testfx:testfx-core:$testFxVersion"
        testCompile "org.testfx:testfx-junit:$testFxVersion"
        testCompile "org.testfx:testfx-legacy:$testFxVersion", {
            exclude group: "junit", module: "junit"
        }
        testCompile "org.testfx:openjfx-monocle:$monocleVersion"
    }
```

**Comment by Adoby7** [comment]
Yes, but I don't know how to find the link of my API. (e.g. in this website https://jcenter.bintray.com/) @marvinchin

**Comment by tshradheya** [comment]
https://bintray.com/jerady/maven/FontAwesomeFX

You can find the dependencies to add in this link. (Look for the gradle dependencies in the link)

**Comment by Adoby7** [comment]
Thank you very much @tshradheya
