### ISSUE TITLE
[W4.3d] Object Diagrams for Class Diagram

### ISSUE THREAD

**Issue by szalata** [nus-cs2103-AY1718S1/forum#20]
Hello,
Doesn't the object diagram in the hint imply that the home address of Bruce and Alfred is same? Shouldn't we instead make two instances of anonymous Address object and connect Bruce to one of them and Alfred to another? I am aware that it might just happen that the address is identical, but while having two different objects with the same values is possible it is not the other way around, thus we, as I think, assume that the address is same. Am I right? The exercise is attached below.
Thank you for help.
![image](https://user-images.githubusercontent.com/17835212/30062825-1e985170-927f-11e7-87c6-660ec4e38e5b.png)

**Comment by damithc** [comment]
You are right, usually we would create two `Address` objects. However, the question requires us to minimize the number of objects and hence the answer uses the same object for both cases. You can think of it as an internal optimizations. In fact this is how Java handles String objects. The following code in fact creates only one String object (to save space) and both variables point to the same "Adam" object internally.
```java
String a = "Adam";
String b = "Adam";
```

**Comment by damithc** [comment]
@arturs68 Just realized that your doubt was caused by an omission in the question. Sorry about that. Corrected it now.
![image](https://user-images.githubusercontent.com/1673303/30093229-872b06e8-92f6-11e7-985b-b5386eead70b.png)
