### ISSUE TITLE
Setup Coveralls

### ISSUE THREAD

**Issue by erik0704** [nus-cs2103-AY1718S1/forum#200]
I have trouble setup coveralls page. Some groups said that they just have to setup travis and the coveralls overage badge will work. 

I got travis to work however my coveralls page instead of 

![screen shot 11-09-17 at 02 12 pm](https://user-images.githubusercontent.com/28505595/32591013-4f903a3e-c558-11e7-97d4-84cb16d45b57.JPG)

It just show me the setup page instead which was quite non-descriptive.
![screen shot 11-09-17 at 02 15 pm](https://user-images.githubusercontent.com/28505595/32591572-a5fd3582-c55a-11e7-997c-11697c5e8d97.JPG)

**Comment by raisa2010** [comment]
Hi there! Have you signed in with your GitHub account and added your repos to the list?

**Comment by erik0704** [comment]
![screen shot 11-09-17 at 03 29 pm](https://user-images.githubusercontent.com/28505595/32593454-f19fedec-c562-11e7-8d68-3933fe3e5f17.JPG)

Yes I have done so. It shows no build though.

![screen shot 11-09-17 at 03 32 pm](https://user-images.githubusercontent.com/28505595/32593497-23abb0a0-c563-11e7-96cc-7dfb1b07ef58.JPG)

**Comment by karrui** [comment]
Have you tried creating a PR/ committing to that branch? Coveralls is not retroactive, it must detect a new commit to the branch.

**Comment by erik0704** [comment]
Yes. However the travis build is currently failing. Does coveralls only detect passing build ?

**Comment by karrui** [comment]
Yes, only passing builds will be processed

Regards, Karrui
________________________________

**Comment by yunpengn** [comment]
The webhook used to trigger Coveralls from Travis CI is almost the last step in a Travis CI build.

Thus, if any test is still failing, the build already terminates before Coveralls in trigged.

**Comment by damithc** [comment]
@erik0704 did it work?

**Comment by erik0704** [comment]
Yes I got it to work after fixing travis checkstyle problems. Thanks everyone for the help.
