### ISSUE TITLE
Does coverage decrease by just editing documentation?

### ISSUE THREAD

**Issue by archthegit** [nus-cs2103-AY1718S1/forum#207]
Hi Prof,
Is it possible for coverage to decrease by a huge margin(-1.3%) if i just added documentation?

Here is a link to the PR:
https://github.com/CS2103AUG2017-T15-B3/main/pull/143

**Comment by karrui** [comment]
If I'm not wrong, Coveralls is based on the current PRs against the master branch. It is possible another PR is causing the drop.

You can see what caused the drop by clicking into the coverage button, or  https://coveralls.io/builds/14139299 for your specific PR
________________________________

**Comment by archthegit** [comment]
Oh okay thank you!
