### ISSUE TITLE
W4.1b Can use Git branching ⭐️

### ISSUE THREAD

**Issue by huiyiiih** [nus-cs2103-AY1718S1/forum#21]
Hello everyone,

I was trying to do the step 9 of the merging of branch. However, I got a different thing from the one showed to us. 

<img width="1280" alt="screen shot 2017-09-06 at 2 26 37 am" src="https://user-images.githubusercontent.com/31040589/30076558-ce40de54-92ab-11e7-8b6e-190e23fbe867.png">

What is the orange coloured line representing?

**Comment by damithc** [comment]
@huiyiiih it looks like you followed the steps correctly. Sometimes the revision tree produced by sourcetree may not look intuitive or exactly like the screenshot given because the Sourcetree uses some algorithm to do the branch layout. You can ignore the colors too.

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
