### ISSUE TITLE
Issue with Travis CI

### ISSUE THREAD

**Issue by iamok97** [nus-cs2103-AY1718S1/forum#212]
Some tests passed locally and on AppVeyor, but cannot pass through Travis CI.

**Comment by iamok97** [comment]
These tests sometimes can be passed on Travis but sometimes cannot.

**Comment by tshradheya** [comment]
`seedu.address.ui.BrowserPanelTest > display FAILED
    java.lang.AssertionError at BrowserPanelTest.java`

I am guessing this is the error as I myself am facing this problem too.

This has happened before and @marvinchin had troubleshooted the problem and is a Travis problem

This is the [link ](https://nus-cs2103.slack.com/archives/C6JMW6SSZ/p1508508497000291?thread_ts=1508476015.000144&cid=C6JMW6SSZ)to the message.

You can use `@Ignore` to avoid checking of that test for now to allow the tests to pass

**Comment by phungtuanhoang1996** [comment]
too many people are testing and sending search requests to google so its denying further search requests. As such our assertequals of expected and actual url cannot pass

**Comment by phungtuanhoang1996** [comment]
Evidence here

`12:52:11.289 [DEBUG] [TestEventLogger]     java.lang.AssertionError: expected:<https://www.google.com.sg/search?safe=off&q=Alice+Pauline&cad=h> but was:<https://ipv4.google.com/sorry/index?continue=https://www.google.com.sg/search%3Fsafe%3Doff%26q%3DAlice%2BPauline%26cad%3Dh&q=EgQ0Nh8LGPrkm9AFIhkA8aeDS2NPyLukuUobk7TQR8W9j7BFGpTXMgFy>`

**Comment by iamok97** [comment]
@tshradheya @phungtuanhoang1996 Thank you! I have solved the problem by temporarily ignoring the check for url.
