### ISSUE TITLE
Test Failure 

### ISSUE THREAD

**Issue by huiyiiih** [nus-cs2103-AY1718S1/forum#213]
Hello guys,

I keep failing 3 test cases:

1. XmlAddressBookStorageTest > readAndSaveAddressBook_allInOrder_success 
2. StorageManagerTest > addressBookReadSave 
3. AddressBookTest > resetData_withValidReadOnlyAddressBook_replacesData 

I can't seem to find out why the errors occur. I checked the comparison failure and there is an extra space for the expected. But I can't seem to find out why the extra space occurs.

<img width="1075" alt="screen shot 2017-11-11 at 23 23 07" src="https://user-images.githubusercontent.com/31040589/32690798-5f33923e-c737-11e7-93f3-e5ea82ccfbb3.png">

**Comment by damithc** [comment]
Provide the link to PR?

**Comment by huiyiiih** [comment]
I haven't PR-ed. Should I PR?

**Comment by huiyiiih** [comment]
https://github.com/CS2103AUG2017-T14-B3/main/pull/103

@damithc

**Comment by damithc** [comment]
Looks like there are some checkstyle errors. You may want to fix them first so that the travis log shows which tests are failing.

**Comment by huiyiiih** [comment]
I have fixed the checkstyle errors. @damithc

**Comment by damithc** [comment]
I assume these tests are failing locally as well. 
One thing you can do is to start a new branch and introduce your changes tiny bit at a time to see which change causes the test failure.

**Comment by huiyiiih** [comment]
I found out the causes, but I am not sure why they would cause failure to the 3 class I mentioned earlier.

**Comment by damithc** [comment]
If you can isolate the minimal code that causes the test failure, you can create a PR with just that code so that others can take a look at it to see if they can spot the cause.

**Comment by huiyiiih** [comment]
I can state where the code that caused it. 

<img width="980" alt="screen shot 2017-11-12 at 14 45 47" src="https://user-images.githubusercontent.com/31040589/32696633-4d597278-c7b8-11e7-909f-2f3b2eef02c5.png">

The code that caused the error is when I added **withRelation("Benson Meier [siblings]")** and **withRelation("Alice Pauline [siblings]")** to the 2 different persons.
