### ISSUE TITLE
Travis failed due to surprising reasons

### ISSUE THREAD

**Issue by tshradheya** [nus-cs2103-AY1718S1/forum#214]
![image](https://user-images.githubusercontent.com/12574756/32691829-bc111cfe-c748-11e7-8e93-772d16ae0334.png)

On merging PR to master in team repo, the master branch of Team repo passed all TRAVIS tests but the PR on the addressbook-level-4 repo is giving these errors.
Our repo doesn't even have these files and I am not sure how these errors are popping up

( I already tried rebuiding and it doesn't help)

Someone please help. Travis is giving so many problems huh 😠 

[PR](https://github.com/nus-cs2103-AY1718S1/addressbook-level4/pull/21)

Edit: I found a PR by some other team which was closed which actually has this file and the PR was closed around the same time we got this error [PR](https://github.com/nus-cs2103-AY1718S1/addressbook-level4/pull/217)

**Comment by damithc** [comment]
Could be a caching issue. Anyway, not to worry about the PR against AB4. It's fine as long as the build is passing in your team fork.

**Comment by tshradheya** [comment]
Is there any way to resolve the caching issue? Could not find anything substantial on googling

**Comment by damithc** [comment]
I restarted your PR but it still failed. I've asked if AB4 devs to take a look but they are likely to busy with their own projects around this time. If you are sure it is not a problem in your repo, just ignore it for the time being. It's not worth spending your time over in this late hour.

**Comment by eugenepeh** [comment]
@tshradheya , is the problem resolved? I see that your PR has passed the travis build.

**Comment by tshradheya** [comment]
Oh yes, its resolved.  Must be the caching error which got corrected on its own.

Thanks a lot for looking into it.

Closing issue as the problem is resolved
