### ISSUE TITLE
Facing problems with travis

### ISSUE THREAD

**Issue by archthegit** [nus-cs2103-AY1718S1/forum#216]
The travis is failing but when i try to take a look. This is all i see. Does anyone else face this problem?

<img width="945" alt="screen shot 2017-11-12 at 12 09 44 pm" src="https://user-images.githubusercontent.com/22144490/32695872-87cf84ee-c7a2-11e7-893e-32c94dea617f.png">

**Comment by damithc** [comment]
Looks like it's a Travis-wide failure. I see a similar result in other PRs too. Let's hope they fix it soon.

**Comment by damithc** [comment]
Seems to be working again.

**Comment by archthegit** [comment]
Okay sure thanks prof!
