### ISSUE TITLE
Issue with Help Window

### ISSUE THREAD

**Issue by iamok97** [nus-cs2103-AY1718S1/forum#218]
Cannot see all the pictures in the Help Window , when I open it in the release file. But I can see these pictures, when I open it locally.

**Comment by damithc** [comment]
Even the `Ui.png` doesn't show? I believe the original AB4 help Window shows `Ui.png` even when run from the jar file.

**Comment by iamok97** [comment]
Hi Prof @damithc 

All the images do not show including the Ui.png
![problem](https://user-images.githubusercontent.com/31087880/32698718-f83a91dc-c7e4-11e7-870d-07ecfb821136.png)

**Comment by damithc** [comment]
I see. Do you have this problem in previous releases? Did you create the jar using gradle as required?

**Comment by Adoby7** [comment]
@damithc Yes, we create Jar file by  `gradlew clean shadowJar`. Is there any other commands that we miss?

**Comment by caoliangnus** [comment]
I think this is why...lol

![image](https://user-images.githubusercontent.com/30979259/32729838-112c8822-c8c0-11e7-937f-7acc729f947c.png)

**Comment by iamok97** [comment]
Sorry, I forget to close this issue. We have solved the problem already. Thank you! @caoliangnus
