### ISSUE TITLE
Travis build fails but allTests pass locally

### ISSUE THREAD

**Issue by taojiashu** [nus-cs2103-AY1718S1/forum#219]
I keep encountering the same three errors in Travis today. But all tests can pass locally in IntelliJ. I suspect it is a Travis issue, so I did an experiment. I pulled from my team's master branch, which passed Travis yesterday afternoon. Then I made a new branch and added a new line of comment to it. And this caused Travis to fail again.
These are the three errors I am encountering right now.
![screenshot 2017-11-12 20 36 30](https://user-images.githubusercontent.com/24546661/32698973-2f17faf6-c7e9-11e7-8959-ac29410003d9.png)
![screenshot 2017-11-12 20 36 56](https://user-images.githubusercontent.com/24546661/32698978-3d266c86-c7e9-11e7-8e92-6af35f88b0cf.png)
This is the link to my [PR](https://github.com/CS2103AUG2017-W13-B1/main/pull/119) and [experimental PR](https://github.com/CS2103AUG2017-W13-B1/main/pull/121).
Do I have to disable them?

**Comment by taojiashu** [comment]
The experimental PR in my team repo didn't go through Travis. But in my own repo, it failed in Travis. The errors are exactly the same as the 3 error above.

**Comment by damithc** [comment]
Are the failures related to browser panel content?

**Comment by taojiashu** [comment]
Yes I updated the facebook feature. However, the test is about google search, so it should not be affected. I added Google Maps feature last week and there was no problem. And my experimental branch did not do anything to the code, and it failed too. I am afraid that my team's master branch will fail in Travis if I rebuild now.

**Comment by damithc** [comment]
It's probably because Google is rejecting search requests due to our builds on Travis servers issuing too many search requests. Try removing the check for the content of the browser panel. It will weaken the test but will allow the test to pass.

**Comment by taojiashu** [comment]
Ok! Thanks Prof!

**Comment by Adoby7** [comment]
@taojiashu Just disable all tests related to Web, using @ignore or commenting them, see this link https://nus-cs2103.slack.com/messages/C6JMW6SSZ/convo/C6JMW6SSZ-1508476015.000144/?thread_ts=1508476015.000144

**Comment by taojiashu** [comment]
@Adoby7 Thank you for your suggestion. I have commented out all the relevant assertions and it can pass now.
