### ISSUE TITLE
Addressbook-level2

### ISSUE THREAD

**Issue by huiyiiih** [nus-cs2103-AY1718S1/forum#23]
Hello everyone,

I have one question to ask. Is there supposed to be 100 errors after building the program that has been forked and cloned?

I tried running it. However, they told me "Error: Could not find or load main class seedu.addressbook.Main". I know I should not run it since there are so many errors after building it.

**Comment by eugenepeh** [comment]
Hello @huiyiiih , have you tried following all the set up instructions on developer guide?

**Comment by damithc** [comment]
There should not be errors. As @eugenepeh mentioned, follow set up instructions carefully. If you still encounter errors, tell us what those errors are (can post a screenshot)

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
