### ISSUE TITLE
Practice exam question 21: composition and cyclical links

### ISSUE THREAD

**Issue by Juxarius** [nus-cs2103-AY1718S1/forum#234]
For question A21,
The practice exam provides a cyclical diagram stating:
This is a correct usage of composition to represent the fact that as Task may consist of smaller tasks.
The answer to this is A, agree, from the module website

However, it is stated that composition cannot be cyclical in one of the LOs, may i clarify this?

![image](https://i.gyazo.com/3966d4b9fb9ff4922c9380469e225db5.png)

**Comment by yunpengn** [comment]
I think the example in textbook and the one in sample paper is a little bit different.

Let's think about it in this way:

- In the textbook (or the _module website_), there is no multiplicity specified, so a folder _certainly_ cannot be a sub-folder of itself.

- But what if the multiplicity is specified, a folder can contain many sub-folders? This makes more sense.

**Comment by damithc** [comment]
Multiplicity is not involved.
The _cyclical link_ here refers to a cycle among objects. A cycle among classes does not necessarily mean a cycle among objects.
![image](https://user-images.githubusercontent.com/1673303/33064296-201fe556-cee0-11e7-94ed-178f5d6da302.png)
The above diagram is correct. The solid diamond prohibits the following cyclical link: `X` has a sub folder `Y` and `Y` has a sub folder of `Z` and `Z` has the previous `X` as a sub folder. As we know, such a cycle is not possible in normal folder structures and therefore the UML diagram matches the situation we want to model.
If we remove the solid diamond and use a normal association instead, the UML diagram will allow such cycles and therefore the diagram does not capture fully the situation we want to model.

This is a bit hard to get your head around at first. Feel free to ask more questions until its clear.

**Comment by Juxarius** [comment]
Just to check if my concepts are right:
1. How then do we differentiate an object diagram from a class diagram since they look so similar?
2. Composition says the part is destroyed when the whole is destroyed. Is the reverse not true? The reverse needs to not be true to support the idea of tasks containing other sub tasks

**Comment by damithc** [comment]
1. open for comments from others
2. The reverse is not necessarily true. Deleting a sub-task does not mean we have to delete the main task.

**Comment by newalter** [comment]
For 1, a direct difference is that object names in an object diagram are in the form `ObjectName:ClassName` and are underlined. You won't find the underline and colon in a class diagram.

**Comment by Juxarius** [comment]
Yea sure but this example in the textbook was said to be an object diagram, and no colon is present

**Comment by newalter** [comment]
@Juxarius I think you misunderstood what Prof Damith said. The example in the textbook was a class diagram. The `composite cyclical link` in *that class diagram* indicates that there cannot be a cycle among objects. On the other hand, if the composition is taken away, there can be cycles among objects now.

**Comment by newalter** [comment]
The line `Composition also implies that there cannot be cyclical links` means there cannot be cyclical links in a corresponding object diagram. The cyclical class diagram shown in the textbook is a correct diagram that dictates the above restriction in the corresponding object diagram.

**Comment by Juxarius** [comment]
Yes, so the cyclical link in a class diagram is not allowed right? So im wondering if the diagram in A21 a class diagram?

Because it looks the same as this one without the multiplicity. And clearly it was allowed in the practice paper but not here, which leads to my qn of why.

So unless any of these are misconceptions, i dont understand why the answer is A

EDIT: So cyclical links are allowed in class diagrams but if we 'instantiate' it to an object diagram, this is not allowed?

**Comment by newalter** [comment]
Cyclical link in a class diagram is ALLOWED. A cyclical link with composition in a class diagram indicates that cyclical link in the corresponding object diagram is not allowed.

Both diagrams in the textbook and the question are class diagram

**Comment by damithc** [comment]
@Juxarius what @newalter said is correct. In the meantime I'll think about how to make the textbook explanation easier to understand.

**Comment by Juxarius** [comment]
okies, i got it now thanks for all your help!
