### ISSUE TITLE
"Could not find or load main class..." - Addressbook-level2

### ISSUE THREAD

**Issue by huiyiiih** [nus-cs2103-AY1718S1/forum#26]
Hello everyone,

There seems to be a problem with my Intellij. After forking and cloning it. I imported the project to Intellij and tried to run it. However, there is this error "Error: Could not find or load main class seedu.addressbook.Main". I did not make any changes to the program. I just tried running it.

<img width="1280" alt="screen shot 2017-09-07 at 3 04 58 pm" src="https://user-images.githubusercontent.com/31040589/30166245-4db597aa-9415-11e7-9910-713bf5be66c1.png">

**Comment by damithc** [comment]
What happens if you click `Build --> Rebuild project`. Any error messages?

**Comment by huiyiiih** [comment]
@damithc After adding JUnit4 to class path there isn't any errors.

**Comment by damithc** [comment]
> @damithc After adding JUnit4 to class path there isn't any errors.

👍

**Comment by huiyiiih** [comment]
There isn't any errors but when I tried to run it the same error appears.

**Comment by huiyiiih** [comment]
Rebuilding it doesn't show me any errors but running it does. @damithc

**Comment by damithc** [comment]
I see. Are you able to run tests using `runtests.sh`?

**Comment by damithc** [comment]
@Zhiyuan-Amos @yamgent have you guys encountered this before?

**Comment by Zhiyuan-Amos** [comment]
@damithc @yamgent I may have encountered this before (can't exactly recall whether this is the exact problem or not because it's been quite a while)

@huiyiiih here's a possible solution:
Can you try to delete the project from your computer and reclone it? I may have encountered this issue before, and this helped me to resolve the issue. ~~Make sure that you select the `build.gradle` file when importing the project, and select the `Use default gradle wrapper (recommended)` option (there are other options, make sure you choose this one) in the next screen.~~

**Comment by damithc** [comment]
> Make sure that you select the build.gradle file when importing the project, and select the Use default gradle wrapper (recommended) option (there are other options, make sure you choose this one) in the next screen.

@Zhiyuan-Amos at level2 students don't use the gradle file. See level2 set up instructions.

**Comment by Zhiyuan-Amos** [comment]
@damithc ah ok. @huiyiiih you can still refer to the comment I made earlier (https://github.com/nus-cs2103-AY1718S1/forum/issues/26#issuecomment-327994007), but ignore the strikethrough portions.

If the solution doesn't work, then I think there's a problem with the `Project Structure`? Not too sure though @yamgent

**Comment by huiyiiih** [comment]
@damithc @Zhiyuan-Amos I will try it out later as I am having lesson now. Will let you know if the problem has been solved. Thank you. :)

**Comment by huiyiiih** [comment]
@damithc How do I run test using runtest.sh? Should I type in the command runtest.sh in the test folder?

**Comment by Zhiyuan-Amos** [comment]
Here: https://github.com/se-edu/addressbook-level2/blob/master/doc/DeveloperGuide.md#testing

**Comment by huiyiiih** [comment]
@Zhiyuan-Amos 
<img width="244" alt="screen shot 2017-09-08 at 2 30 50 pm" src="https://user-images.githubusercontent.com/31040589/30198808-5fbbdd5a-94a2-11e7-86eb-e3d5dba89aea.png">

**Comment by Zhiyuan-Amos** [comment]
Hmm ok, can you try deleting your project, recloning and reimporting it? Be sure to follow the steps for importing the project ^^

**Comment by huiyiiih** [comment]
@Zhiyuan-Amos Alright, I will try again and let you know.

**Comment by huiyiiih** [comment]
@Zhiyuan-Amos I will have to do the add JUnit4 to the class path first right?

**Comment by Zhiyuan-Amos** [comment]
Just follow the steps; in step 9 you will add JUnit4 to the class path :)
https://github.com/se-edu/addressbook-level2/blob/master/doc/DeveloperGuide.md#setting-up

**Comment by okkhoy** [comment]
@Zhiyuan-Amos I face something similar. In my case, IJ didn't automatically build the project. I had to force build. On a second attempt on a different computer, after I made some change to code, build was fired. Only after that I could run the program. Please note, I was using IJ on Linux.  

@huiyiiih can you force a build; or simply add a print statement anywhere in the program to force a build? after that if it works, may be some lead for the devs to investigate.

**Comment by yamgent** [comment]
@huiyiiih Thanks for reporting your issue on the forum!

I noticed that your project is stored inside `~/Documents/2017:18Sem1/CS2103/`. One of your directories' name, `2017:18Sem1`, uses a colon symbol.

You need to rename the directory to `201718Sem1` (i.e. remove the colon), otherwise Java is going to have difficulty finding your project files because colon symbols are not allowed afaik.

Do give this a try and see if there's any other problem after that. Thanks!

**Comment by Zhiyuan-Amos** [comment]
> You need to rename the directory to 201718Sem1 (i.e. remove the colon), otherwise Java is going to have difficulty finding your project files because colon symbols are not allowed afaik.

That's sick bro. Great analysis 👍

**Comment by huiyiiih** [comment]
@Zhiyuan-Amos @yamgent @okkhoy @damithc Thank you all so much. I managed to get it working now. The problem may have been the colon or the "Run All Test" section, I changed the folder name to exclude the colon.

**Comment by angtianlannus** [comment]
@huiyiiih Thank you for asking this question
@Zhiyuan-Amos  Thank you so much for ur advice, it totally solved my problem!

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
