### ISSUE TITLE
📣 Get started on this week's compulsory LO

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY1718S1/forum#29]
Some notes about upcoming compulsory LO `W5.4` Can work with a 2KLoC code base:

* LO instructions have been refined. In particular, **there is a part that you need to do as a team**.
* This LO needs some time to finish; **start it early**.
* Compared to the 1KLoC LO in week 3 (which we accepted as long as the code was working), **acceptance criteria for this LO is stricter**. e.g. code, tests, and docs need to be updated and the work needs to be submitted as a clean PR.
* As you do this LO with your team members, **observe their conduct, helpfulness, technical expertise, etc.** You'll need to submit peer evaluations for your team members in week 6.

**Comment by ChenXiaoman** [comment]
Hi Prof Damith, do we need to work with phase A team or phase B team for this LO? Thanks.

**Comment by damithc** [comment]
Phase A
