### ISSUE TITLE
Intellij IDEA License Activation

### ISSUE THREAD

**Issue by huiyiiih** [nus-cs2103-AY1718S1/forum#3]
Hello everyone,

I would like to know which button should I click, the evaluate for free? It only evaluate free for 30 days. 

<img width="450" alt="screen shot 2017-08-20 at 10 09 42 am" src="https://user-images.githubusercontent.com/31040589/29492003-7213a37c-85a0-11e7-8f1f-dd666444019b.png">

**Comment by okkhoy** [comment]
@huiyiiih Register for a student account here: https://www.jetbrains.com/student/ and use the professional edition if you need to use that.
OR 
Download  the community edition from: 
https://www.jetbrains.com/idea/download/#section=windows (Windows) https://www.jetbrains.com/idea/download/#section=mac (Mac) https://www.jetbrains.com/idea/download/#section=linux (Linux)

I suspect community edition doesn't need activation code.

**Comment by huiyiiih** [comment]
@okkhoy Which one is better? Are there any difference between them?

**Comment by damithc** [comment]
> Which one is better? Are there any difference between them?

Either one is good enough for CS2103. The ultimate edition has [more features](https://www.jetbrains.com/idea/features/editions_comparison_matrix.html) such as support for Java EE (none of the additional features are needed for CS2103) but it takes more resources and has other inconveniences such as getting a student license.

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
