### ISSUE TITLE
Difference between the triangle association and rhombus association in UML diagram

### ISSUE THREAD

**Issue by yangminxingnus** [nus-cs2103-AY1718S1/forum#30]
What differences do they suggest?

I'm saying the association line with a triangle at the end or a rhombus at the end.

**Comment by damithc** [comment]
![image](https://user-images.githubusercontent.com/1673303/30235818-2e97053a-9540-11e7-8b86-343dd8928066.png)

**Comment by damithc** [comment]
I'll leave this for someone who has already studied the relevant LOs (or attended Yesterday's lecture) to give a more specific answer 😈

**Comment by yangminxingnus** [comment]
Ok 😂 though I attended but still don't get that 😂

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
