### ISSUE TITLE
Addressbook-level2 - Source code do not match byte code

### ISSUE THREAD

**Issue by huiyiiih** [nus-cs2103-AY1718S1/forum#31]
Hello everyone,

I was trying to debug after adding some dummy values into the address book. I used the _step into_ function to show me how the program runs. However, when it reaches the line where it shows the person I've added, it does not go into the Address/Email/Phone/Name/Person etc class to show me how each line of code is executed. 

What does it mean "Source code does not match byte code"?

<img width="1280" alt="screen shot 2017-09-09 at 2 01 35 pm" src="https://user-images.githubusercontent.com/31040589/30237656-2631b510-9569-11e7-9471-96dce832e3a1.png">

**Comment by eugenepeh** [comment]
It might be the source code is different from the compiled code, can you try to rebuild the project and debug again?

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
