### ISSUE TITLE
How do we write tests for our exception handlers to see if they're working as expected? Ie. IO errors, Runtime errors.

### ISSUE THREAD

**Issue by zameschua** [nus-cs2103-AY1718S1/forum#33]

**Comment by Zhiyuan-Amos** [comment]
One way is to nest the method call in a try-catch block, and you catch the exception that you are expecting.

```
try {
    methodThatFails();
    fail(); // i.e. if methodThatFails() doesn't throw an Exception, this line will be called, thus failing the test
} catch (SomeException se) {
    // no need to do anything here
}
```

There are other ways too! Take a look at https://stackoverflow.com/questions/156503/how-do-you-assert-that-a-certain-exception-is-thrown-in-junit-4-tests.

In the future, go and Google up first :P You'll find some answers online for sure!

**Comment by zameschua** [comment]
Thanks for the reply, clarified my doubts :)
