### ISSUE TITLE
Passes manual testing, but automated testing returns "NoSuchElementException: No Line Found"

### ISSUE THREAD

**Issue by bokwoon95** [nus-cs2103-AY1718S1/forum#36]
Here's the relevant PR: [https://github.com/nus-cs2103-AY1718S1/addressbook-level2/pull/400](https://github.com/nus-cs2103-AY1718S1/addressbook-level2/pull/400)

I made an enhancement that prompts the user for name, phone, email, address & tags one by one as shown below. This passes manual testing, however it returns “NoSuchElementException: No line found” if I use file redirection with input.txt instead.
<img width="621" alt="screen shot 2017-09-12 at 1 07 56 pm" src="https://user-images.githubusercontent.com/23723357/30309610-be311214-97be-11e7-9cad-ea1660525b04.png">
the compile error
<img width="827" alt="screen shot 2017-09-12 at 1 17 17 pm" src="https://user-images.githubusercontent.com/23723357/30309614-c30c2332-97be-11e7-9e40-c6a7501d8550.png">

Here's what input.txt looks like:
<img width="374" alt="screen shot 2017-09-12 at 1 29 39 pm" src="https://user-images.githubusercontent.com/23723357/30309556-7c574854-97be-11e7-853c-19560495db1c.png">

Seems like it's something to do with Scanner.nextLine() not detecting a next line, but nextLine() is the only way to read in strings with spaces in them. Any idea what is causing this?

**Comment by damithc** [comment]
When using the I/O method of testing, you should not create multiple scanners. Reason: all input text (given in one shot via the file) is swallowed by the first Scanner, leaving nothing for the subsequent scanners.

**Comment by damithc** [comment]
On a general note, the current code is tailored for a CLI interface where each command is stand-alone. Prompting for user input is hard to fit into the current code base, unless you put the code somewhere it doesn't belong, such as what you have done. :-p i.e. Interacting with the user should ~~not~~ be done in one place rather than all over the code base.
EDIT: should not be -> should ~~not~~ be

**Comment by bokwoon95** [comment]
Oh yeah I tried to get the existing system to accept user inputs one by one, but found it too complicated to modify (hence the cheap hack with creating a new class to tack onto the existing 'add person' method).
