### ISSUE TITLE
Creating FXML 

### ISSUE THREAD

**Issue by AngularJiaSheng** [nus-cs2103-AY1718S1/forum#39]
Hi, for w6.2, we need to create some FXML files for the javaFX project. The instruction given is to right click on package and click new and click on FXML. I can't seem to find the FXML option when i do that. Anyone facing the same issue? Thanks!!

**Comment by yamgent** [comment]
When creating the project, did you select "JavaFx Application"? Or was the project created a normal one?

**Comment by AngularJiaSheng** [comment]
Yes. JavaFx Application!
![image](https://user-images.githubusercontent.com/30235910/30473152-f386db68-9a31-11e7-8eeb-80f2c307b4f6.png)

**Comment by AngularJiaSheng** [comment]
This is my scenebuilder path C:\Users\Jason An\AppData\Local\SceneBuilder. But somehow there is error. Thanks!! 
![image](https://user-images.githubusercontent.com/30235910/30473274-6c7a013a-9a32-11e7-8e95-eadf6fd2fb57.png)

**Comment by hansiang93** [comment]
You need to point your "scenebuilder" path to "C:\Users\Jason An\AppData\Local\SceneBuilder\scenebuilder.exe"

**Comment by AngularJiaSheng** [comment]
Yes.. agree, but every time I click on open in scenebuilder, the app will install again. No sure is it suppose to be like that. 
![image](https://user-images.githubusercontent.com/30235910/30474435-42231404-9a36-11e7-841b-64e76f8d5fdc.png)

**Comment by hansiang93** [comment]
You need to point it to the installed scenebuilder.exe, not the installer.

![image](https://user-images.githubusercontent.com/12292130/30474611-d96c7c92-9a36-11e7-9b50-b03d99651539.png)

**Comment by AngularJiaSheng** [comment]
(Y)(Y)(Y) wait ah i try

**Comment by AngularJiaSheng** [comment]
Hey thanks man! it worked. Regarding the FXML file, can just manually set a FXML template:)

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
