### ISSUE TITLE
W2.3d Automated Testing of CLI Apps

### ISSUE THREAD

**Issue by charlesgohck** [nus-cs2103-AY1718S1/forum#4]
![screen shot 2017-08-20 at 4 39 29 pm](https://user-images.githubusercontent.com/15852016/29493318-3735ef46-85c6-11e7-9bdc-00607193c816.png)

<img width="835" alt="screen shot 2017-08-20 at 4 51 56 pm" src="https://user-images.githubusercontent.com/15852016/29493422-013fd59e-85c8-11e7-8c70-90020568e356.png">

<img width="638" alt="screen shot 2017-08-20 at 4 34 11 pm" src="https://user-images.githubusercontent.com/15852016/29493430-5552f53a-85c8-11e7-8efa-97f4aa414146.png">

<img width="483" alt="screen shot 2017-08-20 at 4 38 20 pm" src="https://user-images.githubusercontent.com/15852016/29493298-12749072-85c6-11e7-9cfc-6a24d7d80f4e.png">

![screen shot 2017-08-20 at 4 39 29 pm](https://user-images.githubusercontent.com/15852016/29493450-a41f828c-85c8-11e7-97c4-627e9e08d8d6.png)

In part W2.3d, we are asked to build the project on IntelliJ and then run the program AddressBook and redirect the output to output.txt. I assumed the target directory was from the out/production folder. However, despite building the project successfully I am getting a Could not find or load main class error. I'm a bit confused because there is an AddressBook.class in the production folder. Has anyone encountered a similar issue?

**Comment by jacoblipech** [comment]
Hi! I have similar problem like you! May I know how did you resolve it?

**Comment by charlesgohck** [comment]
Hi Jacob. Once you build your project in IntelliJ IDEA, an out folder will appear. Go to:
out --> production --> youraddressbookfoldername
Set you terminal/bash's current directory to this folder. Then run:
`java seedu.addressbook.AddressBook`
Why run from this directory and why not go straight into the folder with the AddressBook.class and run it from there? I believe it doesn't work because of some build configuration settings. 
@damithc Is this true?

**Comment by damithc** [comment]
> Why run from this directory and why not go straight into the folder with the AddressBook.class and run it from there? I believe it doesn't work because of some build configuration settings.
> @damithc Is this true?

`AddressBook.class` is in the `seedu.addressbook` package. Therefore, you should run it from a place where java runtime can find the `AddressBook.class` by navigating the path `seedu/addressbook/` (because java expects the folder structure to match the package structure).

**Comment by charlesgohck** [comment]
I don't think it is a mac only problem. The documentation on github also advised us to navigate to the out/production/projectrootfolder. 
<img width="912" alt="screen shot 2017-08-20 at 10 46 36 pm" src="https://user-images.githubusercontent.com/15852016/29495826-961d717c-85f9-11e7-8382-73cb44fdf394.png">

> Therefore, you should run it from a place where java runtime can find the AddressBook.class by navigating the path seedu/addressbook/ (because java expects the folder structure to match the package structure).

That's what I thought too, but I kept getting the `Error: Could not find or load main class AddressBook` if I wanted to run the program from the addressbook folder

**Comment by damithc** [comment]
To be clear, you should run it from a location `x` where `x/seedu/addressbook/AddressBook.class` exists. That way, when java runtime looks for `seedu/addressbook/AddressBook.class` relative to the current directory, it is there to be found. If you run it in `seedu/addressbook/` folder, java runtime will try to find the class relative to that folder, and because `seedu/addressbook/seedu/addressbook/AddressBook.class` does not exist, it will fail.

In general, if you want to run a main class that is in a package, you should run it from the parent folder containing the package tree, not in the folder where the `.class` file is.
