### ISSUE TITLE
📣 If your 2KLoC compulsory LO did not meet our requirements

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY1718S1/forum#41]
**If you failed to submit the 2KLoC compulsory LO `W5.4 Can work with a 2KLoC code base` or if your submission did not meet the requirements** (based on tutor feedback during the tutorial or PR review), you will lose all 5 participation marks allocated for phase A. 

However, there is a way to get the 5 marks back: Do an enhancement (can be the same enhancement you did for level 2, or a similar one) to [addressbook-level3](https://github.com/nus-cs2103-AY1718S1/addressbook-level3) and create a new PR against [our repo](https://github.com/nus-cs2103-AY1718S1/addressbook-level3). Ensure that the new PR rectify all the problems noted in the original PR, such as broken/missing JUnit tests. Level 3 does not have I/O tests; that requirement can be omitted.

**Note that the PR title should be same as the original PR** (i.e. same LO ID as before and using the Phase A team ID). The deadline is your week 6 tutorial (i.e. next week).

**Comment by eugenepeh** [comment]
Sorry everyone, please ignore the accidental reference.
