### ISSUE TITLE
getResource() returns null in AddressBook level 3

### ISSUE THREAD

**Issue by syy94** [nus-cs2103-AY1718S1/forum#44]
![image](https://user-images.githubusercontent.com/28534459/30512452-9e19e160-9b22-11e7-9b33-ccc29ef6a70d.png)

This is a fresh clone of the addressbook level 3 repo. However the application cannot start as the 

`Main.class.getResource("ui/mainwindow.fxml")`

keeps returning null.

When I create a new javafx project, 'getResource()' works and the sample application runs.

I tried:

- https://stackoverflow.com/questions/26328040/intellij-idea-getclass-getresource-return-null (did not work)

**Comment by damithc** [comment]
@syy94 did you follow all the steps in the setup instructions. e.g. the step for setting up the working folder

**Comment by syy94** [comment]
Thanks for the advice, everything is working fine now.

I initially checked out using Intellij which helps configure the project such that I do not have to edit any run configurations while allowing all the test cases to pass. However, this caused some problems with the main program.

After I followed the setup instructions, it works. Then out of curiosity I tried to isolate the problem and I found out that Gradle was the one causing this problem.

The problem arises when:

1. checking out via Intellij which detects the project as a Gradle project
2. importing the project and chose the `Import project from external model` Gradle option
3. linking the project to Gradle.
![image](https://user-images.githubusercontent.com/28534459/30513009-6cf7fae8-9b2e-11e7-91fc-4e75ab713a83.png)

So the solution to my problem is follow the setup instructions and do not link the project to Gradle.

**Comment by syy94** [comment]
Accidentally clicked the close issue button.

**Comment by syy94** [comment]
Fixed Gradle.build and moved the .fxml files and .css file such that linking to Gradle will not have getResource() returning null. Commit can be found [here](https://github.com/syy94/addressbook-level3/commit/496ff6495b7e6588b922ab6c3d0a2a5274e2fbed)

**Comment by damithc** [comment]
Closing as this is no longer relevant to other students. Thanks for additional info and troubleshooting attempts @syy94
