### ISSUE TITLE
📣 Phase B team IDs updated in the module website

### ISSUE THREAD

**Issue by damithc** [nus-cs2103-AY1718S1/forum#45]
Phase B team IDs have been added to [the Team ID page in the module website](https://docs.google.com/spreadsheets/d/e/2PACX-1vTSnp6t_MzmNDS2Jg5GPWkHoJmX0ISL_XBz86Z2n_CxvEkwHw4yZCWxaDZbRFb6PBotFQRPZXfreJwI/pubhtml?gid=0&single=true). Please check yours and report here if you notice anything amiss.

![image](https://user-images.githubusercontent.com/1673303/30535264-471698c2-9c94-11e7-92aa-ebf95102c40f.png)

**Comment by thehelpfulbees** [comment]
Should we be using these team IDs or our original ones for PRs?

**Comment by damithc** [comment]
> Should we be using these team IDs or our original ones for PRs? 

You are now in phase B, so use the phase B team ID for PRs this week.

![image](https://user-images.githubusercontent.com/1673303/30544803-4e62cfda-9cba-11e7-80c7-9ce4aec2ce29.png)
