### ISSUE TITLE
Problem running original code

### ISSUE THREAD

**Issue by Juxarius** [nus-cs2103-AY1718S1/forum#47]
When i tried to open the project, it requested me to choose a GRADLE so i selected the recommended option. Before i tried changing any of the programming, i ran the program under JUnit and it passed all tests. However, i cannot run it and an IOException is thrown at my stage.setScene(...) or stage.show() line in the GUI code.
Am i missing any packages that should be installed?

**Comment by damithc** [comment]
Are you referring to addressbook-level3?

**Comment by Juxarius** [comment]
yes i am sir, i have just installed scenebuilder and linked intellij to scenebuilder but the same problem is still there

**Comment by damithc** [comment]
When setting up the project, follow the instructions given in the developer guide of the project. IIRC, you are not supposed to use gradle during the project setup.

**Comment by Juxarius** [comment]
Alright i revert everything and redid according to the dev guide, issue is resolved, thanks
