### ISSUE TITLE
How to configure Travis CI so that gh-pages branch is built automatically

### ISSUE THREAD

**Issue by yunpengn** [nus-cs2103-AY1718S1/forum#51]
I want to make use of the script `deploy_github_pages.sh`

However, I do not know how to set up the so-called `GITHUB_TOKEN`.

Anyone knows about this? Please help. Thxs.

**Comment by damithc** [comment]
It's documented [here](https://nus-cs2103-ay1718s1.github.io/addressbook-level4/UsingTravis.html#enabling-auto-publishing-of-documentation)
Sorry, I didn't realize the documentation in nus-cs2103-AY1718S1/addressbook-level4 was a few commits behind the se-edu, and hence did not include the information you were seeking

**Comment by yunpengn** [comment]
Thxs prof. Got it.
