### ISSUE TITLE
Typo in 2103T website in example code

### ISSUE THREAD

**Issue by tshradheya** [nus-cs2103-AY1718S1/forum#52]
`private ObservableList<person> personData = FXCollections.observableArrayList();
`

`    public ObservableList<person> getPersonData() {
`

In Part 2 of W6.2 , under Observable List, the code given has `person` instead of `Person` for the Type of List

**Comment by damithc** [comment]
Thanks for the bug report @tshradheya 
It's due to a bug in the underlying platform (i.e. `<Text>` becomes `<text>`). I've done a workaround by adding a space around the text (`<Person>` --> `< Person >`)
