### ISSUE TITLE
Help Window in AddressBook Level 4 cannot be opened

### ISSUE THREAD

**Issue by eldonng** [nus-cs2103-AY1718S1/forum#56]
I cant seem to be able to open the help window in AddressBook Level 4. The log seems to show that there is a null pointer exception in the HelpWindow.java, and this line is causing the problem.
String userGuideUrl = getClass().getResource(USERGUIDE_FILE_PATH).toString();

![capture](https://user-images.githubusercontent.com/30952400/30953998-fe58a308-a460-11e7-8b93-3f8e692f93e9.JPG)

By changing the userGuideUrl to the actual path of the document, there is a pop up now, but it still does not show anything, but the null pointer exception is solved.
![capture2](https://user-images.githubusercontent.com/30952400/30954063-503487b4-a461-11e7-944c-98dd266ef361.JPG)

Is this a bug or just my addressbook having the problem?

**Comment by damithc** [comment]
@eldonng while we wait for someone to respond, do double-check to confirm you didn't miss a step in the setup instructions.

**Comment by Zhiyuan-Amos** [comment]
Hey there, would like to check whether you ran the "processResources" task using Gradle? (It's in the set up instructions)

**Comment by eldonng** [comment]
Ok its fixed already thanks! I may have missed out that step sorry.

**Comment by Zhiyuan-Amos** [comment]
-5 marks for not following instructions 👿 😟 haha just kidding 😅

**Comment by eldonng** [comment]
oops.. sorry about that.. because I ran the ./gradle processResources on my repo, but didnt do it inside my group repo, so I had problems for that in the group repo
