### ISSUE TITLE
Should all user stories be tagged with "type.story"?

### ISSUE THREAD

**Issue by yunpengn** [nus-cs2103-AY1718S1/forum#59]
### Project 1.0 Step 1 : Brainstorm user stories

If my team chooses to use GitHub project to document all user stories, since we will create an issue for each user story, should all user stories be tagged with "`type.story`"? I asked this because I feel most of these stories can have the "`type.enhancement`" tag as well.

A little confused about the use of those labels actually.

**Comment by damithc** [comment]
You can exercise your own judgement on these decisions and deviate from the suggested approach (provided you have a good justification). e.g. use a different set of labels.
Suggestion: use `type.enhancement` for things that are smaller than a story e.g. increase font size of person name
