### ISSUE TITLE
Resolving HashMap<String, String> collisions in in LO-Collections

### ISSUE THREAD

**Issue by ZY-Ang** [nus-cs2103-AY1718S1/forum#6]
How strict is the requirement for the LO to be completed in procedural form through a HashMap<String, String> replacement of String[]? I realize that if I have two people, of the exact same name, phone number and email, collisions can happen and they should be treated as two separate Persons. Is it ok if the LO was completed using a wrapper class with an internal HashMap implementation?

**Comment by damithc** [comment]
Do your best to stay within the procedural approach. It's ok for the functionality to have weaknesses if they are hard to fix within the procedural approach. It's a good thing that we encounter limitations/inconveniences like these. It gives us good motivation to look for a better approach, which we'll after one more week.

**Comment by marvinchin** [comment]
Would just like to confirm - The issue described by @ZY-Ang, seems to address the issue of collision when **user details (encoded as a string array) are stored in a hashmap**, with the names of the persons as the keys. 

However, the LO seems to instead suggest that we should be changing the way that we **store a person's details (originally a string array with index 0 containing name, index 1 containing phone number and index 2 containing email address) to a hashmap (with different keys for name, phone number and email address)**. As there is no mention of changing the way that we store the collection of person details, I presume that these details will be stored as an ArrayList of hashmaps. In this case, even if two users have the exact same details, they are still stored as two different instances of hashmaps, in two different indexes of the array and no collision happens.

Would anyone be able to clarify which interpretation is correct, please?

**Comment by ZY-Ang** [comment]
@marvinchin 
My only concern at the time of writing is the **getPersonsWithNameContainingAnyKeyword** method which contains a HashSet implementation which may do something to the program if "persons" are stored as HashMap<String, String>.

```java
//Problem storing in hashset/hashmap:
HashMap<String, String> person1  = new HashMap<String, String>();
person1.put(exampleProperty, "Value");
HashMap<String, String> person2  = new HashMap<String, String>();
person2.put(exampleProperty, "Value");
if (person1.equals(person2) && person2.equals(person1))
    System.out.println("Same " + person1.hashCode() +" "+ person2.hashCode());
else
    System.out.println("Different " + person1.hashCode() +" "+ person2.hashCode());
  
//No problem storing in hashset/hashmap
PClass p1 = new PClass();
p1.prop = "hello";
PClass p2 = new PClass();
p2.prop = "hello";
if (p1.equals(p2) && p2.equals(p1))
    System.out.println("Same " + p1.hashCode() +" "+ p2.hashCode());
else
    System.out.println("Different "+ p1.hashCode() +" "+ p2.hashCode());
```

**Comment by marvinchin** [comment]
@ZY-Ang 
Thanks for clarifying. It seems though, that the hashset used in the getPersonsWithNameContainingAnyKeyword implementation is used to store the set of words in a single person's name at a time.

```java
private static ArrayList<String[]> getPersonsWithNameContainingAnyKeyword(Collection<String> keywords) {
        final ArrayList<String[]> matchedPersons = new ArrayList<>();
        for (String[] person : getAllPersonsInAddressBook()) {
            final Set<String> wordsInName = new HashSet<>(splitByWhitespace(getNameFromPerson(person)));
            if (!Collections.disjoint(wordsInName, keywords)) {
                matchedPersons.add(person);
            }
        }
        return matchedPersons;
    }
```

It appears that the program iterates through each person in the array, creating a hashset of words (not persons) composing the person's name and checks if there is an intersection with the input keywords. IEven if there were two users with the same details/identical hash codes, each person will undergo the matching process mentioned above and will both be appended to the result matchedPersons array.

As these identical persons are not inserted into the same hashtable/hashset at any point (at least, to my observation at this time), it appears that there is no risk of hash collision.
