### ISSUE TITLE
Is anyone else getting the exception "java.lang.IllegalStateException: Location is not set" with JavaFX ?

### ISSUE THREAD

**Issue by shuang-yang** [nus-cs2103-AY1718S1/forum#60]
[Related LO]: JavaFX (w6.2)

[Exception trigger]: when trying to run MainApp.java with javaFX component

[Message]: 
`Caused by: java.lang.IllegalStateException: Location is not set.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at seedu.addressbook.MainApp.initRootLayout(MainApp.java:34)
	at seedu.addressbook.MainApp.start(MainApp.java:21)`

[Tried solutions]:
Upon Google & Stackoverflow searches, it was suggested that the problem is with this line of code:
`loader.setLocation(MainApp.class.getResource("view/PersonOverview.fxml"));`
However, I've tried different ways of writing the file location but still keep getting this error message. 

Is there anyone else who's facing the same problem?

**Comment by tshradheya** [comment]
Did you follow the steps to enable JAVA FX?

**Comment by shuang-yang** [comment]
Yup I followed all the steps. In fact this same problem also pops up when I try to run "Addressbook Level 3" that I directly cloned from the repo, so I think it might be a problem with system configurations... (I'm using a mac by the way)

**Comment by damithc** [comment]
@shuang-yang confirmed you used the build.gradle file when setting up the project?

![image](https://user-images.githubusercontent.com/1673303/31056064-999b7ba2-a6fe-11e7-8ebc-1414c53c1ab4.png)

**Comment by Zhiyuan-Amos** [comment]
> loader.setLocation(MainApp.class.getResource("view/PersonOverview.fxml"));

I think you are missing a `/` before `view` i.e. <pre>MainApp.class.getResource("/view/PersonOverview.fxml")</pre>.

**Comment by shuang-yang** [comment]
Hi @damithc I did use the build.gradle when I open the project, and followed the other steps as well. However interestingly the Addressbook Level 4 seem to work just fine - even though I did not do any modification to it.

@Zhiyuan-Amos I tried this as well... but it didn't work

**Comment by damithc** [comment]
> However interestingly the Addressbook Level 4 seem to work just fine - even though I did not do any modification to it.

@shuang-yang So all's well or something is still not working?

**Comment by shuang-yang** [comment]
@damithc All is well now! thx!

**Comment by Zhiyuan-Amos** [comment]
@shuang-yang you may want to share your solution here so if others face this problem they can resolve it by referring to this thread ^^
