### ISSUE TITLE
Gradle test failure

### ISSUE THREAD

**Issue by erik0704** [nus-cs2103-AY1718S1/forum#61]
I follow the set up instruction and able to get the message `BUILD SUCCESSFUL` after running the command `gradlew processResources` in the console. 

Using IntelliJ JUnit test runner I got all tests to passed

![screen shot 10-01-17 at 10 19 pm](https://user-images.githubusercontent.com/28505595/31055601-e8e02872-a6f7-11e7-912c-bd091cf8d2bf.JPG)

However when I run the Gradle test `gradlew clean allTests` I got a failure
>FAILURE: Build failed with an exception.

![screen shot 10-01-17 at 10 13 pm](https://user-images.githubusercontent.com/28505595/31055479-ff5f5caa-a6f5-11e7-9185-016aa9877853.JPG)
>Could not find tools.jar

I'm not quite sure how to resolve this.

**Comment by damithc** [comment]
Typically, you should start by googling the error message `could not find tools.jar` to see if someone else already faced/solved that problem. :-)

**Comment by erik0704** [comment]
I found a fix that work for me by adding a line in the `gradle.properties` file

`org.gradle.java.home=C:\\Program Files\\Java\\jdk1.8.0_45`

**Comment by lancehaoh** [comment]
This is not the ideal solution I think. I had the same problem and I used this fix. But the extra line caused the build to fail tests on travis. I solved the issue by defining a JAVA_HOME environment variable in my computer. For mac, you have to define it in the config of the shell that you are using (you can check your shell from the command echo $SHELL). For windows, I am not sure but it can be easily googled.

**Comment by erik0704** [comment]
This solution works but I also need to modifying the PATH environment variable to include %JAVA_HOME%\bin
