### ISSUE TITLE
Workflow for improving individual components

### ISSUE THREAD

**Issue by zenghou** [nus-cs2103-AY1718S1/forum#63]
Hello all, 

I understand that each team mate is in charge of different components. However, when we are making improvements to the individual components, changes in the other components might be necessary to test the change by executing the program. For instance, when I add a new method removeTag in model, I would need to make changes to UI and logic so I can enter it as a command. Am I supposed to make this change then when I am only in charge of the model component? What would be the recommended workflow if I am not supposed to make this change? 

On another note, for this week's improvements, do we have to write JUnit tests as well?

**Comment by damithc** [comment]
@zenghou 
1. It is fine if you want to do a change that goes beyond one component, but it is safer to start with a smaller change that is limited to one component.
2. You can use JUnit tests to test the changes to a component. For example, there is no need to type commands in the GUI to test a change in the Model.
3. Yes, it is recommended that you write JUnit tests for your changes.
Hope this clarifies. Feel free to ask for further clarifications.

**Comment by zenghou** [comment]
Ok, thank you Prof! Your explanation clarified a lot.
