### ISSUE TITLE
UserGuide.html in .gitignore

### ISSUE THREAD

**Issue by newalter** [nus-cs2103-AY1718S1/forum#65]
Currently the help command opens the UserGuide.html file in src/main/resources/docs
As I update the userguide, I updated both UserGuide.adoc and UserGuide.html but then I realised that UserGuide.html is in .gitignore. 
May I know why UserGuide.html is in .gitignore? Is it because the .html file was generated from the .adoc file?

**Comment by damithc** [comment]
> Is it because the .html file was generated from the .adoc file?

That's correct @newalter. There is no need to modify the html files manually. Refer to the relevant section of the Developer Guide to find out how to set up the auto-generation of html files.
