### ISSUE TITLE
Decreased Coverage

### ISSUE THREAD

**Issue by zenghou** [nus-cs2103-AY1718S1/forum#66]
Hello folks, 

I finished adding the suggested improvement to the model component (i.e. deleteTag) and created a PR to my team's repo. The PR passed both Travis and App Veyor CI but the code coverage fell. Am I supposed to proceed to merge or do something about it? I checked the code coverage and it appears that the additional 3 lines of code I have written for deleteTag method are not covered. 

<img width="699" alt="screen shot 2017-10-05 at 2 22 27 pm" src="https://user-images.githubusercontent.com/23148645/31214491-f32aff12-a9dd-11e7-994e-d2eeb08651db.png">

**Comment by damithc** [comment]
@zenghou You can ignore coverage drops for the time being.

**Comment by zenghou** [comment]
@damithc Ok prof thanks!
