### ISSUE TITLE
Headless testing with IntelliJ?

### ISSUE THREAD

**Issue by Xenonym** [nus-cs2103-AY1718S1/forum#69]
Hey all!

Does anyone know of a way to run headless tests from intelliJ? Headless only seems to work when I run them from Gradle; IntelliJ still runs with a visible GUI.

**Comment by danielbrzn** [comment]
Hi, not sure if this counts, but you can run it through the console inside IntelliJ.

Use the command "gradlew clean headless allTests"

**Comment by Zhiyuan-Amos** [comment]
> Hi, not sure if this counts, but you can run it through the console inside IntelliJ.Use the command "gradlew clean headless allTests"

That's still running using Gradle isn't it haha :P

@Xenonym try adding `-Dtestfx.headless=true` in your VM options in Run/Debug Configurations. (The image below shows only for `StatusBarFooterTest`, so make sure you are editing the configuration for all tests ^^)

![image](https://user-images.githubusercontent.com/19281514/31259435-263a4b1a-aa79-11e7-962e-236480ecf40a.png)

**Comment by Xenonym** [comment]
@Zhiyuan-Amos thanks for the suggestion! However, adding the command line flag results in really strange behaviour: the window doesn't show but my mouse is still moving around :O

**Comment by Zhiyuan-Amos** [comment]
![image](https://user-images.githubusercontent.com/19281514/31260471-bdab981c-aa80-11e7-8272-4062742b0dd8.png)

Alright updated solution: This is in your `build.gradle` file. Just do `-Dattributename=attributevalue` for all 5 of these. Then it should work fine ^^

(don't ask me what this code does :P idk either HAHA)

**Comment by Xenonym** [comment]
thanks @Zhiyuan-Amos! Adding those attributes work :D
