### ISSUE TITLE
Which project language level should I use?

### ISSUE THREAD

**Issue by huiyiiih** [nus-cs2103-AY1718S1/forum#7]
Hello everybody,

I would like to know on which project language level should I use? I tried the different levels, but all of them give me errors.

<img width="1026" alt="screen shot 2017-08-24 at 12 20 50 am" src="https://user-images.githubusercontent.com/31040589/29626736-53f79e7e-8862-11e7-8fb9-b77285085ec7.png">

I received this error while trying to run the address book.main().

<img width="1271" alt="screen shot 2017-08-24 at 12 22 42 am" src="https://user-images.githubusercontent.com/31040589/29626755-6407080e-8862-11e7-9c27-08d2e092fc09.png">

**Comment by okkhoy** [comment]
@huiyiiih please use `8 - Lambdas, type annotations etc.,`

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
