### ISSUE TITLE
Using GitHub Wiki in place of html asciidocs for user guide.

### ISSUE THREAD

**Issue by ZY-Ang** [nus-cs2103-AY1718S1/forum#71]
Is it possible for us to use the github wiki for user guides instead of the current github pages implementation?

**Comment by damithc** [comment]
While we have no objections, there are some complications you have to consider:
* wiki works as a separate repo. your work in the wiki will not be captured into our grading when we analyze the repo. Similarly, change to the wiki does not appear as PRs under your name, which reduces the visibility of your work.
* When using asciidoc, project portfolio page can auto-include some parts from the user/dev guide. I don't think the same can be done with wiki. You'll end up having to duplicate some work.
* With the current set up, you can generate pdf files for CS2101 and CS2103 submissions from the same set of source files. I'm not sure it will be as convenient if you use wiki.

**Comment by ZY-Ang** [comment]
@damithc 
- Our workflow does not change. Docs are merged into master branch on a feature update, albeit with minor changes to match the wiki format, so marking is no issue. We only update the wiki by merging or (copy pasting) stuff into the wiki repo after it has been merged in our main master branch.
- The reason why I'm asking is because CS2101 is apparently fine with the wiki format for the **User guide**. I'm not sure what pdf I need to generate. The current asciidoc gh-pages are in a generated format that we feel are not on par with that of the wiki. We wanted to do a bunch of stuff to the docs like adding sidebars for ease of navigation and felt the wiki could do that extremely easily, on top of removing the need to manually manage layout. Does CS2103 strictly require pdf submissions for the **User guide**?
- Also, not sure what you mean by project portfolio page can auto-include ... We are still using asciidocs for the wiki pages so I'm unsure what you mean?

**Comment by damithc** [comment]
@ZY-Ang  you can give it a try. We are fine as long as you comply with our submission requirements. Yes, CS2103 requires [pdf submission for v1.5](https://nus-cs2103.github.io/website/admin/index.html#admin-project-v15)
