### ISSUE TITLE
CloudRail import builds with IDEA GUI button but not Gradle

### ISSUE THREAD

**Issue by icehawker** [nus-cs2103-AY1718S1/forum#72]
I used CloudRail's API manual install, because automatic integration is only officially supported with Maven. (Their support staff had provided me with testing phase code for automatic import with Gradle, but it did not work)

The import works (ie. no red underlines etc. on IDEA when using CloudRail-exclusive commands), and the program **compiles with IDEA's GUI build button**.
But the import no longer works and program **will not compile when "gradlew allTests" is entered**, ie. command line compilation through Gradle. The compile error pointed to CloudRail, claimed it was not imported.

CloudRail technical support has opened a ticket and is trying to resolve the issue as well. Not sure if it is just my IDEA's configuration causing the issue, any ideas welcome.

**Comment by damithc** [comment]
@icehawker 
* Let's wait to see if anyone has any helpful inputs on your problem.
* Note that use of third party software is at your own risk and there are some [prerequisites you need to comply with](https://nus-cs2103.github.io/website/admin/index.html#policy-reuse) before using any external software in the project.

**Comment by damithc** [comment]
@icehawker Is this issue still relevant? Close if not.

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
