### ISSUE TITLE
Travis CI keeps failing on team repo but not on individual repo

### ISSUE THREAD

**Issue by karrui** [nus-cs2103-AY1718S1/forum#74]
Can anyone help? This is the reason Travis supplied: 
```
ERROR:src/main/resources/docs/UserGuide.html:541: no newline at EOF.
ERROR:src/main/resources/docs/stylesheets/coderay-asciidoctor.css:88: no newline at EOF.
```

However, the team repo does not even have the files it is referencing...

**Comment by damithc** [comment]
It might help if you post the link to the problematic repo here.

**Comment by karrui** [comment]
This is one of the PRs that is failing Travis. Weird thing is, only some PRs are affected and some are not. It is very weird. 
https://github.com/CS2103AUG2017-F11-B3/main/pull/11

**Comment by pyokagan** [comment]
The simplest solution is to not commit the files inside the `src/main/resources/docs/` directory.

What's happening is that committing the files in that directory makes them tracked by Git, which thus subjects them to the repository-wide checks. The Travis CI build runs `./gradlew assemble` which overwrites the files in that directory (without the newline at EOF), and thus these files thus subsequently cause "no newline at EOF" errors.

**Comment by eugenepeh** [comment]
Resolved for now, the `src/main/resources/docs/` is actually in .gitignore though so a command to fix gitignore if you accidentally tracked ignore files is

*Note: Save your work on another branch first before trying this out*

>git rm -rf --cached .
git add .
