### ISSUE TITLE
CustomImportOrder

### ISSUE THREAD

**Issue by huiyiiih** [nus-cs2103-AY1718S1/forum#75]
Hello guys,

I am trying to solve the Travis CI in my team repo. However, the errors were "CustomImportOrder".
Does anyone know what is this error about? This happened after I pull the commits my team members made and merged with the master to my local repo. I added my part and committed them and pull request. However, Travis CI failed so I read the errors related to my part and tried to solve the checkstyle for my part. However, the weird thing is some of the errors that appeared in my PR have already passed Travis CI in my team member's pull request. 

I do not understand this:
<img width="968" alt="screen shot 2017-10-07 at 02 31 04" src="https://user-images.githubusercontent.com/31040589/31292874-a02fc33a-ab07-11e7-85b5-777d3a86a6f9.png">
What does it mean by "Imports without groups should be placed at the end of the import list: ..."?

Please advise me on this issue. Thank you so much. 

Previous:
https://travis-ci.org/CS2103AUG2017-T14-B3/addressbook-level4/builds/284317308?utm_source=github_status&utm_medium=notification

Solved some errors:
https://travis-ci.org/CS2103AUG2017-T14-B3/addressbook-level4/builds/284335044?utm_source=github_status&utm_medium=notification

**Comment by damithc** [comment]
Make sure you follow the [import order as specified by the coding standard](https://oss-generic.github.io/process/codingStandards/CodingStandard-Java.html#package-and-import-statements).

There is a [import-related configuration you need to do in your Intellij](https://github.com/nus-cs2103-AY1718S1/addressbook-level4/blob/master/docs/DeveloperGuide.adoc#14-configurations-to-do-before-writing-code) too.

**Comment by huiyiiih** [comment]
Thank you Prof Damith for the links. I have made necessary changes to them however there is still two specific errors I got that I am unsure of how should I edit. 

<img width="1187" alt="screen shot 2017-10-10 at 22 02 52" src="https://user-images.githubusercontent.com/31040589/31390662-124198fc-ae07-11e7-9ebb-a2738a615b61.png">
This is the error I got regarding java.awt.*;. I have check online regarding this class and it sees like there are over 12 packages and 370 classes. I am unsure of how I should go about listing the classes explicitly since there are so many of them. 

I am also having problem with this error.
<img width="1194" alt="screen shot 2017-10-10 at 22 08 42" src="https://user-images.githubusercontent.com/31040589/31390899-b1642d64-ae07-11e7-9c1e-5a60c15f63f5.png">

**Comment by damithc** [comment]
> I am unsure of how I should go about listing the classes explicitly since there are so many of them.

You need to list _only_ those classes you have used in your code. 

> I am also having problem with this error.

Overloaded methods in a class should appear together.
Instead of this,
```java
void foo(){
}

void bar(){
}

void foo(String s){
}
```
it should be,

```java
void foo(){
}

void foo(String s){
}

void bar(){
}
```

**Comment by huiyiiih** [comment]
Thank you Prof Damith, I would also like to know why does it seems like I am the only one that has all this issues?

I thought I have finished solving those but when I tried to run Travis in terminal, a whole new bunch of CustomImportOrder errors came. 

Is there a way to get it done faster? None of my group members seem to have this problem. It is taking up a lot of time as well.

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
