### ISSUE TITLE
Error is setting up CheckStyle-IDEA

### ISSUE THREAD

**Issue by huiyiiih** [nus-cs2103-AY1718S1/forum#76]
Hello everyone,

I tried setting up the CheckStyle-IDEA following the steps in the link.
However, there are errors when I tried to click Next after changing the checkstyle configuration to the one in address book-level4/config/checkstyle/checkstyle.xml.

<img width="501" alt="screen shot 2017-10-07 at 13 47 33" src="https://user-images.githubusercontent.com/31040589/31305207-778be2ce-ab66-11e7-8a79-9f882597e2db.png">

**Comment by damithc** [comment]
@huiyiiih This may be relevant https://github.com/se-edu/addressbook-level4/issues/715

**Comment by hansiang93** [comment]
@huiyiiih  Try this:

Switch between checkstyle 8.0 and 8.1, and click outside of the window to "lock in" the selection.
If this doesnt work, try clicking "apply" for the 8.1 selection, then go back into the preference and add the xml again.

**Comment by damithc** [comment]
Closing because this seems to be resolved. Please reopen if still not resolved.
