### ISSUE TITLE
Unable to access CS2103 repo despite giving the correct GitHub ID

### ISSUE THREAD

**Issue by Chng-Zhi-Xuan** [nus-cs2103-AY1718S1/forum#8]
Hi, 

I would like to elaborate that I got my ID from the API 
https://api.github.com/users/YOUR_USER_NAME

I have placed my ID "31084833" in the IVLE survey (since 2 weeks ago) but have yet to receive any invitation to the repo

I don't want to miss the deadline :(

**Comment by damithc** [comment]
This is what we were asking for:
![image](https://user-images.githubusercontent.com/1673303/29737800-212aecbc-8a47-11e7-9781-c66fef46ddd8.png)

I should have said `User Name` in the survey. My bad. I did not realize GitHub also has a separate user ID.

**Comment by damithc** [comment]
Please edit your submission to the pre-module survey to provide the correct user name.
