### ISSUE TITLE
Permission to use Graph Stream library

### ISSUE THREAD

**Issue by joanneong** [nus-cs2103-AY1718S1/forum#80]
Hi Prof and module coordinators, since we are supposed to request for library permissions before using it, can we check if it is fine to use Graph Stream for our CS2103 project? This is because our project involves graphs and graph visualisation, so we hope to utilise this library for that. More details about the library can be found at: http://graphstream-project.org/

**Comment by damithc** [comment]
Approved.

**Comment by joanneong** [comment]
Thank you Prof for the prompt response!
