### ISSUE TITLE
JavaFX exception thrown when I try to change Set<Tag> updatedTags

### ISSUE THREAD

**Issue by Juxarius** [nus-cs2103-AY1718S1/forum#81]
Hi all,

I have been troubleshooting this problem for a few days and i still cannot find the cause of the exception thrown. Im trying to manipulate how the EditCommand#createEditedPerson::updatedTags is handled. However, even when i pass the syntax correctly according to intellij, there is a runtime error when i try to use methods of the Set class like removeAll() remove() addAll() clear(). The irony is that the runtime exception thrown is
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException at (points to 40+ different locations)

Even the debugger runs the Set method called perfectly but just suddenly jumps out to the logic model right before completing the code
e.g. updatedTags.removeAll(tagsToBeRemoved.get())
- tagsToBeRemoved is an Optional<Set\<Tag\>> and was confirmed to exist with isPresent() before running this.
- get() method runs, according to debugger
- removeAll() runs, according to debugger
- right after the removeAll method runs, the debugger jumps out to a finally statement, showing an exception is thrown, thus i cannot trace the exception thrown

Thanks for any help in advance

**Comment by jelneo** [comment]
Hi there, the problem seems to occur when JavaFX elements are changed in a thread different from the FX application thread. Try [this](https://stackoverflow.com/questions/39422477/how-do-i-solve-java-lang-illegalstateexception-in-a-gui-created-using-javafx).

**Comment by Juxarius** [comment]
Hi Jel,

Thanks for the swift reply, I tried the runLater method which still gave me an error pointing to the same code. However, the error was more directive as it reminded me that my Set was made an unmodifiableSet by one of the getters function, and that was the reason i cannot edit anything. I will have to consider the consequences of making the set modifiable now but after changeing it to a normal Set, the errors are all resolved.

**Comment by Zhiyuan-Amos** [comment]
> removeAll() runs, according to debugger

> right after the removeAll method runs, the debugger jumps out to a finally statement, showing an exception is thrown, thus i cannot trace the exception thrown

This actually means that `removeAll()` doesn't run successfully actually. :P 

> I will have to consider the consequences of making the set modifiable now

If you make the `Set` modifiable (I suppose you are making the `Set<Tag>` in the `Person` class modifiable), it means that your `Person`'s tags can be edited directly through the getter method and the `Set#add(Object)` method i.e. you don't need to go through `setTags(Set<Tag>)` in the `Person` class to edit the `Person`'s tags. This can be quite risky if you aren't careful as your encapsulation is weakened. As such, you should try to think of a way to work with the unmodifiable Set.

**Comment by Juxarius** [comment]
@Zhiyuan-Amos I believe the `Set<Tag>` in the `Person` class was already open to public editting in the first place with a public setter? What i couldnt understand was why the `getTags()` method was returning an unmodifiableSet as the result which was what i changed. In this case, I should be getting a copy of the tags Set right? And not the actual Set which exists inside the person class. So any editting only affects the copy and not the actual set. But the actual set gets modified anyway since the `setTags` is used.

EDIT: Just did a debugging run to track the hash, it is different from the one inside the person class, so I should be receiving a copy right?

Please do explain how encapsulation is compromised here.

**Comment by Zhiyuan-Amos** [comment]
> I believe the Set<Tag> in the Person class was already open to public editting in the first place with a public setter? 

You are right.

> What i couldnt understand was why the getTags() method was returning an unmodifiableSet as the result which was what i changed.

Suppose this:
```
Set<Tag> personTags = person.getTags();
personTags.add(new Tag("someTagValue"));
```

This code results in a person's tags being modified not through the **setter method**, but through the **getter method**.

> Please do explain how encapsulation is compromised here.

As a result, encapsulation is compromised because we generally want the fields of an object to be updated through the **setter method** only.

> In this case, I should be getting a copy of the tags Set right? And not the actual Set which exists inside the person class.

This method (i.e. defensive copy) is one way of doing it. Just be sure that you are making a copy of the `Set`, and not a copy of the individual `Tag`s.

> What i couldnt understand was why the getTags() method was returning an unmodifiableSet

As mentioned above, returning an `unmodifiableSet` causes the tags field to be immutable, thus preventing a person's tags from being modified through the getter method.

**Comment by Juxarius** [comment]
By this logic, that getters give u the reference to the original data, wouldnt every single getter method require an immutable data return?
Unless im mistaken about what is happening

**Comment by Zhiyuan-Amos** [comment]
> By this logic, that getters give u the reference to the original data, wouldnt every single getter method require an immutable data return?

The other fields in `Person` class (`Name`, `Phone` etc) are immutable. As I've mentioned above, there's benefits of allowing these fields to be immutable.
Regarding other pros & cons of mutable vs immutable, I will let someone else respond :P How about you mention one of the cons of returning immutable objects then?

**Comment by Juxarius** [comment]
Immutable objects are a self-restriction which hinders me from implementing my function. It expresses the intention of the initial development idea that the object passed should not be changed, disallowing any distortion of the data. However, one thing to be made clear here is the difference between using an unmodified object and an immutable one, a fairly satisfactory answer can be found here
https://stackoverflow.com/questions/8892350/immutable-vs-unmodifiable-collection
as well as the difference between unmodifiable and final (constants).
In this case, i did not see the point of passing an unmodifiable set from a getter function because there is no way i am modifying the original data from editing the returned data. In c++ this might have been possible with pointers and pass-by-references but i dont see how this mistake might be made in Java

**Comment by Zhiyuan-Amos** [comment]
> Immutable objects are a self-restriction which hinders me from implementing my function.

Can you post your code here? I'm just curious whether there's other ways of implementing your function while conforming to this restriction.

I will not comment on the rest of your reply as mentioned above ^^

**Comment by Juxarius** [comment]
```
Set<Tag> updatedTags = personToEdit.getTags();

        if (editPersonDescriptor.getTagsToDel().isPresent()) {
            for (Tag tag : editPersonDescriptor.getTagsToDel().get()) {
                if (tag.getTagName().equals("all")) {
                    updatedTags.clear();
                }
            }
            updatedTags.removeAll(editPersonDescriptor.getTagsToDel().get());
        }

        if (editPersonDescriptor.getTags().isPresent()) {
            updatedTags.addAll(editPersonDescriptor.getTags().get());
        }
```
i also changed the getTags implementation in Person to return me a Set instead of an unmodifiableSet
` public Set<Tag> getTags() {
        return tags.get().toSet();
    }`

**Comment by Zhiyuan-Amos** [comment]
Oh thanks for mentioning the distinction between `immutable` and `unmodifiable`; I shouldn't have used both terms interchangeably.

```
Set<Tag> updatedTags = new HashSet<>();

if (editPersonDescriptor.getTagsToDel().isPresent()) {
    Set<Tag> tagsToDelete = editPersonDescriptor.getTagsToDel().get();
    if (!tagsToDelete.contains(new Tag("all"))) {
        for (Tag tag : personToEdit.getTags()) {
            if (tagsToDelete.contains(tag)) {
                continue;
            }
            updatedTags.add(tag);
        }
    }
}
```

Does this work? I don't think you need to modify `getTags()` implementation in `Person`.
This is a sloppy way of doing it; I trust that you can refactor this well enough ^^
