### ISSUE TITLE
Permission to use YouTube Data API

### ISSUE THREAD

**Issue by jhchia** [nus-cs2103-AY1718S1/forum#84]
Hello Prof, is it okay if my group uses the YouTube Data API for our project? We plan to use it to extract information like channel views, subscriber count of YouTubers to show in the app. This is the link to the API: [https://developers.google.com/youtube/v3/docs/](url)

**Comment by damithc** [comment]
Approved

**Comment by jhchia** [comment]
Thank you, Prof 😃
