### ISSUE TITLE
Checkstyle indentation errors

### ISSUE THREAD

**Issue by khooroko** [nus-cs2103-AY1718S1/forum#87]
![image](https://user-images.githubusercontent.com/28438978/31532590-cedefd2c-b020-11e7-91dc-9365d4f2fa7a.png)

Has anyone faced the above checkstyle error in which there seems to be no correct indentation level, or any solutions or workarounds to it? Below screenshot is the piece of code that gives this problem (the second run was done with this version)

![image](https://user-images.githubusercontent.com/28438978/31532583-c45cc74e-b020-11e7-95c6-07daa6b86f5c.png)

**Comment by nicholaschuayunzhi** [comment]
Hi Wei Ping, the `(` on `line 123, 127 and 129` should be on the line below.

**Comment by khooroko** [comment]
![image](https://user-images.githubusercontent.com/28438978/31533463-eeb870ac-b024-11e7-8e79-ea8cdeb20b8a.png)
I tried that before, and it results in different checkstyle errors

**Comment by khooroko** [comment]
Workaround found with help of @jaivigneshvenugopal : create a Label and a Text variable inside and assign the node/subnode to them before setting their texts from those variables
