### ISSUE TITLE
Remark does not show on UI

### ISSUE THREAD

**Issue by zenghou** [nus-cs2103-AY1718S1/forum#88]
Hi guys,

I'm having a bit of an issue with debugging for Remark Command. The application currently accepts the remark command and reflects that there is a new command is added, but it does not reflect on the person card. I am also failing the JUnit test addressBook_dataFileDoesNotExist_loadSampleData. 

<img width="668" alt="screen shot 2017-10-13 at 4 43 56 pm" src="https://user-images.githubusercontent.com/23148645/31537757-dc30b3d4-b035-11e7-8c40-10132ffe7c6b.png">

Can I get some general directions on where I could start debugging? This is the link to my PR: https://github.com/CS2103AUG2017-F11-B4/main/pull/17

Thanks in advance!

**Comment by Zhiyuan-Amos** [comment]
You can start by verifying whether the corresponding `PersonCard`'s `remark` is empty or not, after you have executed the `Remark` command. This helps to verify whether the binding has been done properly. I.e. if the `Person` backing the `PersonCard` has the `remark`, but it's not being displayed on the `PersonCard`, then it means there's something wrong with the binding / display. Whereas if the `Person` doesn't have the `remark` at all, then there's something wrong with the execution of `RemarkCommand`

**Comment by damithc** [comment]
@zenghou solved?

**Comment by zenghou** [comment]
@damithc Yes Prof, @Zhiyuan-Amos reviewed my PR instead so I commented there instead. I've fixed the bug (-:

**Comment by damithc** [comment]
Thanks @Zhiyuan-Amos
