### ISSUE TITLE
Unable to make a release

### ISSUE THREAD

**Issue by nicholaschuayunzhi** [nus-cs2103-AY1718S1/forum#89]
With reference to 6.2 Making a Release in addresbooklevel-4 developer guide

```
Making a Release

Here are the steps to create a new release.

.  Update the version number in MainApp.java
.  Generate a JAR file UsingGradle
.  Tag the repo with the version number. e.g. v0.1
.  Create a new release using GitHub and upload the JAR file you created.
```
My team is unable to tag the repo with version number v1.1 as the tag already points to an older commit `914eaa6`.

![image](https://user-images.githubusercontent.com/22221132/31541598-c9893330-b041-11e7-9b66-dd87d7cb8aea.png)

How should we proceed with the tagging/making a release?

**Comment by damithc** [comment]
oops, didn't realize the tag already exists. You can use something similar e.g. `V1.1` or `v.1.0`
