### ISSUE TITLE
Some tests failing in headless mode only 

### ISSUE THREAD

**Issue by philemontan** [nus-cs2103-AY1718S1/forum#90]
Hi, I would appreciate it if anyone can assist with this problem i am facing.
Some tests seem to be failing on headless mode only (locally, and on Travis), but all pass when run in IDE (right click -> run all tests). These tests seem to be completely unrelated to the feature i have implemented, and none are modified in my PR. 

PR for reference: https://github.com/T11-B1/addressbook-level4/pull/46

Here are the failing tests: 

![image](https://user-images.githubusercontent.com/28558102/31546900-e01518ce-b057-11e7-8294-81891ab4616b.png)

**Comment by damithc** [comment]
Are you using Windows or Mac?

Let's wait to see if anyone can help some useful info on this. In the meantime, some side comments:
* Committing authentication info (passwords/client-secrets) into a public repo is not recommended.
* Use of any third party API needs to be approved first. On that front, we don't allow connecting to cloud servers that you run yourself. Only public services of repute like Google APIs will be approved.

**Comment by philemontan** [comment]
Hey Prof,

I'm using Windows. 

Regarding the use of third party API, I am currently using the Google People API, along with its OAuth client library, if you will approve of it. 

Point noted on the storing of client-secrets, i will remove it, as i only require the client ID. 

Also, I am not connecting to any cloud servers, but Google's OAuth2 protocol requires a valid non-localhost redirect url to append the authentication token to, which i then extract directly from the BrowserPanel. Something like a google search URL will also work fine as the redirect url, but I felt it would be insecure, so I am simply using a dummy url hosted on heroku. No functionality is implemented by this dummy url. Please let me know if this is okay, thanks!

**Comment by damithc** [comment]
> Regarding the use of third party API, I am currently using the Google People API, along with its OAuth client library, if you will approve of it.

Should be OK, but post the request in the forum first. I would like others to know what external software are being used, as a form of inspiration.



> Also, I am not connecting to any cloud servers, but Google's OAuth2 protocol requires a valid non-localhost redirect url to append the authentication token to, which i then extract directly from the BrowserPanel. Something like a google search URL will also work fine as the redirect url, but I felt it would be insecure, so I am simply using a dummy url hosted on heroku. No functionality is implemented by this dummy url. Please let me know if this is okay, thanks!

Should be ok too if the app doesn't need the heroku server to be up all the time. The idea is the app should work for a long time to come without requiring additional servers to be running.

**Comment by eugenepeh** [comment]
Hi @philemontan,
the failure you're encountering seems to be all Ui related. 
So my guess is that the your browser panel have some issue connecting to the GoogleApi service which leads to GuiRobot time out and fails all the Gui related tests subsequently. 

To fix this, you can probably start by commenting out codes that have high possibility of causing this error and try to fix them locally. Start by your browser panel, and also build.gradles 
>compile 'com.google.apis:google-api-services-people:v1-rev149-1.23.0' 

sometimes it fails when they couldn't fetch the api you're requesting

**Comment by philemontan** [comment]
Hi @eugenepeh, 

The problem was indeed related to that dependency: 'compile 'com.google.apis:google-api-services-people:v1-rev149-1.23.0''

I have since added the Jars into a lib directory manually, and the build has succeeded on travis. 

Thanks for your help!

**Comment by danielbrzn** [comment]
Hi @philemontan,
I have just run into this problem as well. Do you have any idea why that dependency causes the UI tests to fail?

**Comment by philemontan** [comment]
Hey @danielbrzn , 
Not a clue, but i think eugene gave a good guess on the cause. A solution is just to add it as a local dependency.

**Comment by danielbrzn** [comment]
Hi @philemontan,
Yeah, I have done so and it works perfectly now. Never thought a gradle dependency could cause UI tests to fail. I'm implementing the an import feature using the API. Do you have any tips on storing the client secrets? I currently have it in a json file that's on the public repo (and this is not ideal), but according to [Google](https://developers.google.com/identity/protocols/OAuth2), in the context of installed applications, the client secret is not a secret.

**Comment by philemontan** [comment]
Hey @danielbrzn 
I think you should only require the client ID for import requests. You can probably afford to remove the client secret off your repo entirely.
