### ISSUE TITLE
Request to use Google People API for importing of contacts 

### ISSUE THREAD

**Issue by philemontan** [nus-cs2103-AY1718S1/forum#91]
Hey Prof @damithc , 
This is a request to use the Google People API for importing of contacts, as mentioned in the other thread. 

I will be using Google API client library for java (added as a Gradle dependency): 'com.google.apis:google-api-services-people:v1-rev149-1.23.0' , to read/write contacts to Google Contacts. 

OAuth2 is done using the existing BrowserPanel. 

Please let me know if you have any other queries!

**Comment by damithc** [comment]
Approved.
