### ISSUE TITLE
Converting ASCII Doc to HTML file and updating it as offline doc

### ISSUE THREAD

**Issue by itsdickson** [nus-cs2103-AY1718S1/forum#94]
Hi everyone, 

As mentioned on top, I wish to convert an ASCII doc to a HTML file, and include it with the offlineDeployDocs. 

![image](https://user-images.githubusercontent.com/30717938/31574040-6bf44ce2-b0f9-11e7-9442-c0c4ee8a4587.png)

I followed the steps above and ran asciidoctor which converted my created adoc file to html, but I wish to include it into the resources/docs folder so as to use it to create a new window just like HelpWindow.

![image](https://user-images.githubusercontent.com/30717938/31574059-e814e6ce-b0f9-11e7-8e41-a3de0c89632a.png)

Above is the location of the file where I want my HTML file to be at. I realise that deployOfflineDocs only updates the offline user guide, and I wish to do the same for my HTML file, so that it gets updated as well. 

Thanks for the help!

**Comment by damithc** [comment]
While waiting for a definite solution, one thing you can try is to figure out how the UserGuide.html get copied into the resources folder (and do the same for your file). You could start by doing a project-wide search for the string `UserGuide.html` to see if it is mentioned in any of the files, especially gradle-related files.

**Comment by Zhiyuan-Amos** [comment]
<img width="332" alt="screen shot 2017-10-14 at 7 03 52 pm" src="https://user-images.githubusercontent.com/19281514/31575144-7950203c-b112-11e7-9818-e30b146920d6.png">

Update this segment in `build.gradle`. :)

**Comment by itsdickson** [comment]
Thank you! I managed to get it to work based on Zhiyuan's comment. 

Thank you Prof and Zhiyuan :)
