### ISSUE TITLE
Updating UserGuide.html

### ISSUE THREAD

**Issue by thehelpfulbees** [nus-cs2103-AY1718S1/forum#96]
My apologies for having to create this thread as I saw there is a similar one from a few days ago, but I couldn't quite understand what was happening there. I'm wanting to update UserGuide.html (which pops up when you use the 'help' command) to include documentation for features that have been added into the project – maybe I missed a memo on how to do this, but I can't figure it out?

By inspection I can tell that the file is autogenerated... the thread from a few days ago suggested using asciidoctor or namesearching UserGuide.html, but I couldn't find anything else this way. Can anyone point me in the right direction? Cheers ^_^

**Comment by Zhiyuan-Amos** [comment]
> By inspection I can tell that the file is autogenerated

You are right :P 

Take a closer look at #94, the answer is in the question actually. :P I'll give you an even clearer hint, it's in the last paragraph.

**Comment by damithc** [comment]
@thehelpfulbees You can use Gradle to run various project _tasks_ such as running tests, generating required resources. Converting from adoc to html is one of those things gradle can do. Read the developer guide to find out more.

**Comment by thehelpfulbees** [comment]
After a bit of investigation, Gradle doesn't seem quite as scary as I first thought – I figured out how to run the deployOfflineDocs task. Thank you very much for your help!
