### ISSUE TITLE
GUI does not open

### ISSUE THREAD

**Issue by szalata** [nus-cs2103-AY1718S1/forum#97]
I have been working on a new command and at some point the GUI stopped showing up when i try to run the app. I thought that it must be some bug in my code, even though all the tests pass, so I have checked out the branch from before all the modifications. Unfortunately it didnt change anything. Still all tests pass, but when I try to run the app, everything seems to be ok and app's icon shows on the taskbar, but I do not see the app's window.
Could you please indicate what might be wrong?

**Comment by szalata** [comment]
Here is the log:

Oct 15, 2017 10:40:31 PM seedu.address.MainApp init
INFO: =============================[ Initializing AddressBook ]===========================
Oct 15, 2017 10:40:31 PM seedu.address.MainApp initConfig
INFO: Using config file : config.json
Oct 15, 2017 10:40:31 PM seedu.address.MainApp initPrefs
INFO: Using prefs file : preferences.json
Oct 15, 2017 10:40:31 PM seedu.address.commons.core.LogsCenter init
INFO: currentLogLevel: INFO
Oct 15, 2017 10:40:32 PM seedu.address.MainApp start
INFO: Starting AddressBook V0.6.0ea
Oct 15, 2017 10:40:32 PM seedu.address.ui.UiManager start
INFO: Starting UI...

**Comment by damithc** [comment]
I remember there was a case like this before and someone suggested deleting the preferences.json.

**Comment by szalata** [comment]
Thank you for the help. It worked. I thought I have heard of this problem, but could not find it among the issues. I'm sorry for duplicating.
